files = ["ddr_Transact.vhd",
         "Interrupts.vhd",
         "rx_CplD_Channel.vhd",
         "rx_MRd_Channel.vhd",
         "rx_usDMA_Channel.vhd",
         "Tx_Output_Arbitor.vhd",
         "wb_transact.vhd",
         "DMA_Calculate.vhd",
         "rx_dsDMA_Channel.vhd",
         "rx_MWr_Channel.vhd",
         "tlpControl.vhd",
         "tx_Transact.vhd",
         "DMA_FSM.vhd",
         "Registers.vhd",
         "RxIn_Delays.vhd",
         "rx_Transact.vhd",
         "tx_Mem_Reader.vhd",
         "wb_mem.vhd"]
