../../ip_cores/pcie/7k325ffg900/bram_x64.vhd
../../ip_cores/pcie/7k325ffg900/eb_fifo_counted_resized.vhd
../../ip_cores/pcie/7k325ffg900/mbuf_128x72.vhd
../../ip_cores/pcie/7k325ffg900/prime_FIFO_plain.vhd
../../ip_cores/pcie/7k325ffg900/sfifo_15x128.vhd

../../modules/pcie/common/v6abb64Package_efifo_elink.vhd
../../modules/pcie/common/DDR_Blinker.vhd
../../modules/pcie/common/DMA_Calculate.vhd
../../modules/pcie/common/DMA_FSM.vhd
../../modules/pcie/common/FF_tagram64x36.vhd
../../modules/pcie/common/FIFO_Wrapper.vhd
../../modules/pcie/common/FIFO_Wrapper_Loopback.vhd
../../modules/pcie/common/Interrupts.vhd
../../modules/pcie/common/PCIe_UserLogic_00.vhd
../../modules/pcie/common/Registers.vhd
../../modules/pcie/common/RxIn_Delays.vhd
../../modules/pcie/common/Tx_Output_Arbitor.vhd
../../modules/pcie/common/bram_DDRs_Control.vhd
../../modules/pcie/common/bram_DDRs_Control_Loopback.vhd
../../modules/pcie/common/rx_CplD_Channel.vhd
../../modules/pcie/common/rx_MRd_Channel.vhd
../../modules/pcie/common/rx_MWr_Channel.vhd
../../modules/pcie/common/rx_Transact.vhd
../../modules/pcie/common/rx_dsDMA_Channel.vhd
../../modules/pcie/common/rx_usDMA_Channel.vhd
../../modules/pcie/common/tlpControl.vhd
../../modules/pcie/common/tx_Mem_Reader.vhd
../../modules/pcie/common/tx_Transact.vhd
../../top/pcie/bpm_pcie_k7.vhd

