board.v

../../sim/pcie/sys_clk_gen.v
../../sim/pcie/sys_clk_gen_ds.v

../../sim/pcie/xilinx_pcie_2_1_rport_7x.v
../../sim/pcie/pcie_2_1_rport_7x.v
../../sim/pcie/pcie_axi_trn_bridge.v
../../sim/pcie/pci_exp_usrapp_com.v
../../sim/pcie/pci_exp_usrapp_tx.v
../../sim/pcie/pci_exp_usrapp_cfg.v
../../sim/pcie/pci_exp_usrapp_rx.v
../../sim/pcie/pci_exp_usrapp_pl.v

../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gt_wrapper.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gtp_pipe_rate.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gtp_pipe_reset.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_qpll_wrapper.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_qpll_drp.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_qpll_reset.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_rxeq_scan.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_eq.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_clock.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_drp.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_rate.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_reset.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_user.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_sync.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pipe_wrapper.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gt_rx_valid_filter_7x.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gt_top.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_gt_top_pipe_mode.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_bram_top_7x.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_brams_7x.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_bram_7x.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_7x.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_pipe_pipeline.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_pipe_lane.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_pipe_misc.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_tx_thrtl_ctl.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_rx.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_rx_null_gen.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_rx_pipeline.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_tx_pipeline.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_tx.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_axi_basic_top.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core_pcie_top.v
../../ip_cores/pcie/7k325ffg900/pcie_core/source/pcie_core.v

