files = [
    "axis_interconnect_v1_1_arb_rr.v",
    "axis_interconnect_v1_1_axisc_arb_responder.v",
    "axis_interconnect_v1_1_axisc_decoder.v",
    "axis_interconnect_v1_1_axisc_downsizer.v",
    "axis_interconnect_v1_1_axis_clock_converter.v",
    "axis_interconnect_v1_1_axisc_register_slice.v",
    "axis_interconnect_v1_1_axisc_sample_cycle_ratio.v",
    "axis_interconnect_v1_1_axisc_sync_clock_converter.v",
    "axis_interconnect_v1_1_axisc_transfer_mux.v",
    "axis_interconnect_v1_1_axisc_upsizer.v",
    "axis_interconnect_v1_1_axis_data_fifo.v",
    "axis_interconnect_v1_1_axis_dwidth_converter.v",
    "axis_interconnect_v1_1_axis_interconnect_16x16_top.v",
    "axis_interconnect_v1_1_axis_interconnect.v",
    "axis_interconnect_v1_1_axis_register_slice.v",
    "axis_interconnect_v1_1_axis_subset_converter.v",
    "axis_interconnect_v1_1_axis_switch_arbiter.v",
    "axis_interconnect_v1_1_axis_switch.v",
    "axis_interconnect_v1_1_dynamic_datapath.v",
    "axis_interconnect_v1_1_dynamic_priority_encoder.v",
    "axis_interconnect_v1_1_mux_enc.v",
    "axis_interconnect_v1_1_util_aclken_converter.v",
    "axis_interconnect_v1_1_util_aclken_converter_wrapper.v",
    "axis_interconnect_v1_1_util_axis2vector.v",
    "axis_interconnect_v1_1_util_vector2axis.v"
]

