/*
  Register definitions for slave core: FMC ADC 250MS/s core registers

  * File           : fmc250m_4ch_regs.h
  * Author         : auto-generated by wbgen2 from wb_fmc250m_4ch_regs.wb
  * Created        : Fri Apr 15 16:48:45 2016
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE wb_fmc250m_4ch_regs.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_WB_FMC250M_4CH_REGS_WB
#define __WBGEN2_REGDEFS_WB_FMC250M_4CH_REGS_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Status register */

/* definitions for field: MMCM locked status in reg: Status register */
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_MMCM_LOCKED WBGEN2_GEN_MASK(0, 1)

/* definitions for field: FMC power good status in reg: Status register */
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_PWR_GOOD WBGEN2_GEN_MASK(1, 1)

/* definitions for field: FMC board present status in reg: Status register */
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_PRST   WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Reserved in reg: Status register */
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_RESERVED_MASK WBGEN2_GEN_MASK(3, 28)
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_RESERVED_SHIFT 3
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 3, 28)
#define WB_FMC_250M_4CH_CSR_FMC_STATUS_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 3, 28)

/* definitions for register: Trigger control */

/* definitions for field: Direction in reg: Trigger control */
#define WB_FMC_250M_4CH_CSR_TRIGGER_DIR       WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Termination Control in reg: Trigger control */
#define WB_FMC_250M_4CH_CSR_TRIGGER_TERM      WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Trigger Value in reg: Trigger control */
#define WB_FMC_250M_4CH_CSR_TRIGGER_TRIG_VAL  WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Reserved in reg: Trigger control */
#define WB_FMC_250M_4CH_CSR_TRIGGER_RESERVED_MASK WBGEN2_GEN_MASK(3, 29)
#define WB_FMC_250M_4CH_CSR_TRIGGER_RESERVED_SHIFT 3
#define WB_FMC_250M_4CH_CSR_TRIGGER_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 3, 29)
#define WB_FMC_250M_4CH_CSR_TRIGGER_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 3, 29)

/* definitions for register: Monitor and FMC status control register */

/* definitions for field: Enable test data in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_TEST_DATA_EN WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Led 1 in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_LED1      WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Led 2 in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_LED2      WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Led 3 in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_LED3      WBGEN2_GEN_MASK(3, 1)

/* definitions for field: Monitor device in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_MON_DEV_MASK WBGEN2_GEN_MASK(4, 1)
#define WB_FMC_250M_4CH_CSR_MONITOR_MON_DEV_SHIFT 4
#define WB_FMC_250M_4CH_CSR_MONITOR_MON_DEV_W(value) WBGEN2_GEN_WRITE(value, 4, 1)
#define WB_FMC_250M_4CH_CSR_MONITOR_MON_DEV_R(reg) WBGEN2_GEN_READ(reg, 4, 1)

/* definitions for field: Reserved in reg: Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_MONITOR_RESERVED_MASK WBGEN2_GEN_MASK(5, 27)
#define WB_FMC_250M_4CH_CSR_MONITOR_RESERVED_SHIFT 5
#define WB_FMC_250M_4CH_CSR_MONITOR_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 5, 27)
#define WB_FMC_250M_4CH_CSR_MONITOR_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 5, 27)

/* definitions for register: Clock distribution control register */

/* definitions for field: Si 571 Output Enable in reg: Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_SI571_OE WBGEN2_GEN_MASK(0, 1)

/* definitions for field: AD9510 PLL function in reg: Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_PLL_FUNCTION WBGEN2_GEN_MASK(1, 1)

/* definitions for field: AD9510 PLL Status in reg: Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_PLL_STATUS WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Reference Clock Selection in reg: Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_CLK_SEL WBGEN2_GEN_MASK(3, 1)

/* definitions for field: Reserved in reg: Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_RESERVED_MASK WBGEN2_GEN_MASK(4, 28)
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_RESERVED_SHIFT 4
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 4, 28)
#define WB_FMC_250M_4CH_CSR_CLK_DISTRIB_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 4, 28)

/* definitions for register: Global ADC Status register */

/* definitions for field: FMC ADC clock chains in reg: Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_ADC_STA_CLK_CHAINS_MASK WBGEN2_GEN_MASK(0, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_CLK_CHAINS_SHIFT 0
#define WB_FMC_250M_4CH_CSR_ADC_STA_CLK_CHAINS_W(value) WBGEN2_GEN_WRITE(value, 0, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_CLK_CHAINS_R(reg) WBGEN2_GEN_READ(reg, 0, 4)

/* definitions for field: Reserved in reg: Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_CLK_CHAINS_MASK WBGEN2_GEN_MASK(4, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_CLK_CHAINS_SHIFT 4
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_CLK_CHAINS_W(value) WBGEN2_GEN_WRITE(value, 4, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_CLK_CHAINS_R(reg) WBGEN2_GEN_READ(reg, 4, 4)

/* definitions for field: FMC ADC Data chains in reg: Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_ADC_STA_DATA_CHAINS_MASK WBGEN2_GEN_MASK(8, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_DATA_CHAINS_SHIFT 8
#define WB_FMC_250M_4CH_CSR_ADC_STA_DATA_CHAINS_W(value) WBGEN2_GEN_WRITE(value, 8, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_DATA_CHAINS_R(reg) WBGEN2_GEN_READ(reg, 8, 4)

/* definitions for field: Reserved in reg: Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_DATA_CHAINS_MASK WBGEN2_GEN_MASK(12, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_DATA_CHAINS_SHIFT 12
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_DATA_CHAINS_W(value) WBGEN2_GEN_WRITE(value, 12, 4)
#define WB_FMC_250M_4CH_CSR_ADC_STA_RESERVED_DATA_CHAINS_R(reg) WBGEN2_GEN_READ(reg, 12, 4)

/* definitions for field: FMC ADC packet size in reg: Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_ADC_STA_ADC_PKT_SIZE_MASK WBGEN2_GEN_MASK(16, 16)
#define WB_FMC_250M_4CH_CSR_ADC_STA_ADC_PKT_SIZE_SHIFT 16
#define WB_FMC_250M_4CH_CSR_ADC_STA_ADC_PKT_SIZE_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define WB_FMC_250M_4CH_CSR_ADC_STA_ADC_PKT_SIZE_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Global ADC Control register */

/* definitions for field: Reset/Update ADC clock chains delay in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_UPDATE_CLK_DLY WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Reset/Update ADC data chains delay in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_UPDATE_DATA_DLY WBGEN2_GEN_MASK(1, 1)

/* definitions for field: Reset ADCs in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RST_ADCS  WBGEN2_GEN_MASK(2, 1)

/* definitions for field: Reset Div ADCs in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RST_DIV_ADCS WBGEN2_GEN_MASK(3, 1)

/* definitions for field: Sleep ADCs in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_SLEEP_ADCS WBGEN2_GEN_MASK(4, 1)

/* definitions for field: Reserved in reg: Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RESERVED_MASK WBGEN2_GEN_MASK(5, 27)
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RESERVED_SHIFT 5
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 5, 27)
#define WB_FMC_250M_4CH_CSR_ADC_CTL_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 5, 27)

/* definitions for register: Channel 0 status register */

/* definitions for field: Channel 0 current ADC value in reg: Channel 0 status register */
#define WB_FMC_250M_4CH_CSR_CH0_STA_VAL_MASK  WBGEN2_GEN_MASK(0, 16)
#define WB_FMC_250M_4CH_CSR_CH0_STA_VAL_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH0_STA_VAL_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define WB_FMC_250M_4CH_CSR_CH0_STA_VAL_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved in reg: Channel 0 status register */
#define WB_FMC_250M_4CH_CSR_CH0_STA_RESERVED_MASK WBGEN2_GEN_MASK(16, 16)
#define WB_FMC_250M_4CH_CSR_CH0_STA_RESERVED_SHIFT 16
#define WB_FMC_250M_4CH_CSR_CH0_STA_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define WB_FMC_250M_4CH_CSR_CH0_STA_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Channel 0 fine delay register */

/* definitions for field: ADC clock chain delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(0, 5)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_CLK_CHAIN_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 5)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 5)

/* definitions for field: Reserved in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(5, 3)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_CHAIN_DLY_SHIFT 5
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 5, 3)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 5, 3)

/* definitions for field: ADC data chain delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(8, 5)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DATA_CHAIN_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 5)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 5)

/* definitions for field: Reserved in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(13, 3)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_CHAIN_DLY_SHIFT 13
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 13, 3)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 13, 3)

/* definitions for field: Increment ADC clock chains delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_INC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(16, 1)

/* definitions for field: Decrement ADC clock chains delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DEC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(17, 1)

/* definitions for field: Reserved in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_INCDEC_DLY_MASK WBGEN2_GEN_MASK(18, 6)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_INCDEC_DLY_SHIFT 18
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 18, 6)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_CLK_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 18, 6)

/* definitions for field: Increment ADC data chains delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_INC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(24, 1)

/* definitions for field: Decrement ADC data chains delay in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_DEC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(25, 1)

/* definitions for field: Reserved in reg: Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_INCDEC_DLY_MASK WBGEN2_GEN_MASK(26, 6)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_INCDEC_DLY_SHIFT 26
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 26, 6)
#define WB_FMC_250M_4CH_CSR_CH0_FN_DLY_RESERVED_DATA_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 26, 6)

/* definitions for register: Channel 0 coarse delay register */

/* definitions for field: Falling edge data delay in reg: Channel 0 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_FE_DLY_MASK WBGEN2_GEN_MASK(0, 2)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_FE_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 2)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 2)

/* definitions for field: Reserved in reg: Channel 0 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_FE_DLY_MASK WBGEN2_GEN_MASK(2, 6)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_FE_DLY_SHIFT 2
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 2, 6)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 2, 6)

/* definitions for field: Regular data delay in reg: Channel 0 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RG_DLY_MASK WBGEN2_GEN_MASK(8, 2)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RG_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 2)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 2)

/* definitions for field: Reserved in reg: Channel 0 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_RG_DLY_MASK WBGEN2_GEN_MASK(10, 22)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_RG_DLY_SHIFT 10
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 10, 22)
#define WB_FMC_250M_4CH_CSR_CH0_CS_DLY_RESERVED_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 10, 22)

/* definitions for register: Channel 1 status register */

/* definitions for field: Channel 1 current ADC value in reg: Channel 1 status register */
#define WB_FMC_250M_4CH_CSR_CH1_STA_VAL_MASK  WBGEN2_GEN_MASK(0, 16)
#define WB_FMC_250M_4CH_CSR_CH1_STA_VAL_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH1_STA_VAL_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define WB_FMC_250M_4CH_CSR_CH1_STA_VAL_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved in reg: Channel 1 status register */
#define WB_FMC_250M_4CH_CSR_CH1_STA_RESERVED_MASK WBGEN2_GEN_MASK(16, 16)
#define WB_FMC_250M_4CH_CSR_CH1_STA_RESERVED_SHIFT 16
#define WB_FMC_250M_4CH_CSR_CH1_STA_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define WB_FMC_250M_4CH_CSR_CH1_STA_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Channel 1 fine delay register */

/* definitions for field: ADC clock chain delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(0, 5)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_CLK_CHAIN_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 5)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 5)

/* definitions for field: Reserved in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(5, 3)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_CHAIN_DLY_SHIFT 5
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 5, 3)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 5, 3)

/* definitions for field: ADC data chain delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(8, 5)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DATA_CHAIN_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 5)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 5)

/* definitions for field: Reserved in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(13, 3)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_CHAIN_DLY_SHIFT 13
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 13, 3)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 13, 3)

/* definitions for field: Increment ADC clock chains delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_INC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(16, 1)

/* definitions for field: Decrement ADC clock chains delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DEC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(17, 1)

/* definitions for field: Reserved in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_INCDEC_DLY_MASK WBGEN2_GEN_MASK(18, 6)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_INCDEC_DLY_SHIFT 18
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 18, 6)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_CLK_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 18, 6)

/* definitions for field: Increment ADC data chains delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_INC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(24, 1)

/* definitions for field: Decrement ADC data chains delay in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_DEC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(25, 1)

/* definitions for field: Reserved in reg: Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_INCDEC_DLY_MASK WBGEN2_GEN_MASK(26, 6)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_INCDEC_DLY_SHIFT 26
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 26, 6)
#define WB_FMC_250M_4CH_CSR_CH1_FN_DLY_RESERVED_DATA_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 26, 6)

/* definitions for register: Channel 1 coarse delay register */

/* definitions for field: Falling edge data delay in reg: Channel 1 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_FE_DLY_MASK WBGEN2_GEN_MASK(0, 2)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_FE_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 2)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 2)

/* definitions for field: Reserved in reg: Channel 1 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_FE_DLY_MASK WBGEN2_GEN_MASK(2, 6)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_FE_DLY_SHIFT 2
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 2, 6)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 2, 6)

/* definitions for field: Regular data delay in reg: Channel 1 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RG_DLY_MASK WBGEN2_GEN_MASK(8, 2)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RG_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 2)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 2)

/* definitions for field: Reserved in reg: Channel 1 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_RG_DLY_MASK WBGEN2_GEN_MASK(10, 22)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_RG_DLY_SHIFT 10
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 10, 22)
#define WB_FMC_250M_4CH_CSR_CH1_CS_DLY_RESERVED_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 10, 22)

/* definitions for register: Channel 2 status register */

/* definitions for field: Channel 2 current ADC value in reg: Channel 2 status register */
#define WB_FMC_250M_4CH_CSR_CH2_STA_VAL_MASK  WBGEN2_GEN_MASK(0, 16)
#define WB_FMC_250M_4CH_CSR_CH2_STA_VAL_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH2_STA_VAL_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define WB_FMC_250M_4CH_CSR_CH2_STA_VAL_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved in reg: Channel 2 status register */
#define WB_FMC_250M_4CH_CSR_CH2_STA_RESERVED_MASK WBGEN2_GEN_MASK(16, 16)
#define WB_FMC_250M_4CH_CSR_CH2_STA_RESERVED_SHIFT 16
#define WB_FMC_250M_4CH_CSR_CH2_STA_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define WB_FMC_250M_4CH_CSR_CH2_STA_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Channel 2 fine delay register */

/* definitions for field: ADC clock chain delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(0, 5)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_CLK_CHAIN_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 5)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 5)

/* definitions for field: Reserved in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(5, 3)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_CHAIN_DLY_SHIFT 5
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 5, 3)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 5, 3)

/* definitions for field: ADC data chain delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(8, 5)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DATA_CHAIN_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 5)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 5)

/* definitions for field: Reserved in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(13, 3)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_CHAIN_DLY_SHIFT 13
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 13, 3)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 13, 3)

/* definitions for field: Increment ADC clock chains delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_INC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(16, 1)

/* definitions for field: Decrement ADC clock chains delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DEC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(17, 1)

/* definitions for field: Reserved in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_INCDEC_DLY_MASK WBGEN2_GEN_MASK(18, 6)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_INCDEC_DLY_SHIFT 18
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 18, 6)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_CLK_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 18, 6)

/* definitions for field: Increment ADC data chains delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_INC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(24, 1)

/* definitions for field: Decrement ADC data chains delay in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_DEC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(25, 1)

/* definitions for field: Reserved in reg: Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_INCDEC_DLY_MASK WBGEN2_GEN_MASK(26, 6)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_INCDEC_DLY_SHIFT 26
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 26, 6)
#define WB_FMC_250M_4CH_CSR_CH2_FN_DLY_RESERVED_DATA_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 26, 6)

/* definitions for register: Channel 2 coarse delay register */

/* definitions for field: Falling edge data delay in reg: Channel 2 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_FE_DLY_MASK WBGEN2_GEN_MASK(0, 2)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_FE_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 2)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 2)

/* definitions for field: Reserved in reg: Channel 2 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_FE_DLY_MASK WBGEN2_GEN_MASK(2, 6)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_FE_DLY_SHIFT 2
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 2, 6)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 2, 6)

/* definitions for field: Regular data delay in reg: Channel 2 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RG_DLY_MASK WBGEN2_GEN_MASK(8, 2)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RG_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 2)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 2)

/* definitions for field: Reserved in reg: Channel 2 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_RG_DLY_MASK WBGEN2_GEN_MASK(10, 22)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_RG_DLY_SHIFT 10
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 10, 22)
#define WB_FMC_250M_4CH_CSR_CH2_CS_DLY_RESERVED_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 10, 22)

/* definitions for register: Channel 3 status register */

/* definitions for field: Channel 3 current ADC value in reg: Channel 3 status register */
#define WB_FMC_250M_4CH_CSR_CH3_STA_VAL_MASK  WBGEN2_GEN_MASK(0, 16)
#define WB_FMC_250M_4CH_CSR_CH3_STA_VAL_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH3_STA_VAL_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define WB_FMC_250M_4CH_CSR_CH3_STA_VAL_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved in reg: Channel 3 status register */
#define WB_FMC_250M_4CH_CSR_CH3_STA_RESERVED_MASK WBGEN2_GEN_MASK(16, 16)
#define WB_FMC_250M_4CH_CSR_CH3_STA_RESERVED_SHIFT 16
#define WB_FMC_250M_4CH_CSR_CH3_STA_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define WB_FMC_250M_4CH_CSR_CH3_STA_RESERVED_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Channel 3 fine delay register */

/* definitions for field: ADC clock chain delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(0, 5)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_CLK_CHAIN_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 5)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 5)

/* definitions for field: Reserved in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_CHAIN_DLY_MASK WBGEN2_GEN_MASK(5, 3)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_CHAIN_DLY_SHIFT 5
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 5, 3)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 5, 3)

/* definitions for field: ADC data chain delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(8, 5)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DATA_CHAIN_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 5)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 5)

/* definitions for field: Reserved in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_CHAIN_DLY_MASK WBGEN2_GEN_MASK(13, 3)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_CHAIN_DLY_SHIFT 13
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_CHAIN_DLY_W(value) WBGEN2_GEN_WRITE(value, 13, 3)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_CHAIN_DLY_R(reg) WBGEN2_GEN_READ(reg, 13, 3)

/* definitions for field: Increment ADC clock chains delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_INC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(16, 1)

/* definitions for field: Decrement ADC clock chains delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DEC_CLK_CHAIN_DLY WBGEN2_GEN_MASK(17, 1)

/* definitions for field: Reserved in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_INCDEC_DLY_MASK WBGEN2_GEN_MASK(18, 6)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_INCDEC_DLY_SHIFT 18
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 18, 6)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_CLK_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 18, 6)

/* definitions for field: Increment ADC data chains delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_INC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(24, 1)

/* definitions for field: Decrement ADC data chains delay in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_DEC_DATA_CHAIN_DLY WBGEN2_GEN_MASK(25, 1)

/* definitions for field: Reserved in reg: Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_INCDEC_DLY_MASK WBGEN2_GEN_MASK(26, 6)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_INCDEC_DLY_SHIFT 26
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_INCDEC_DLY_W(value) WBGEN2_GEN_WRITE(value, 26, 6)
#define WB_FMC_250M_4CH_CSR_CH3_FN_DLY_RESERVED_DATA_INCDEC_DLY_R(reg) WBGEN2_GEN_READ(reg, 26, 6)

/* definitions for register: Channel 3 coarse delay register */

/* definitions for field: Falling edge data delay in reg: Channel 3 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_FE_DLY_MASK WBGEN2_GEN_MASK(0, 2)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_FE_DLY_SHIFT 0
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 0, 2)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 0, 2)

/* definitions for field: Reserved in reg: Channel 3 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_FE_DLY_MASK WBGEN2_GEN_MASK(2, 6)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_FE_DLY_SHIFT 2
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_FE_DLY_W(value) WBGEN2_GEN_WRITE(value, 2, 6)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_FE_DLY_R(reg) WBGEN2_GEN_READ(reg, 2, 6)

/* definitions for field: Regular data delay in reg: Channel 3 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RG_DLY_MASK WBGEN2_GEN_MASK(8, 2)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RG_DLY_SHIFT 8
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 8, 2)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 8, 2)

/* definitions for field: Reserved in reg: Channel 3 coarse delay register */
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_RG_DLY_MASK WBGEN2_GEN_MASK(10, 22)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_RG_DLY_SHIFT 10
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_RG_DLY_W(value) WBGEN2_GEN_WRITE(value, 10, 22)
#define WB_FMC_250M_4CH_CSR_CH3_CS_DLY_RESERVED_RG_DLY_R(reg) WBGEN2_GEN_READ(reg, 10, 22)
/* [0x0]: REG Status register */
#define WB_FMC_250M_4CH_CSR_REG_FMC_STATUS 0x00000000
/* [0x4]: REG Trigger control */
#define WB_FMC_250M_4CH_CSR_REG_TRIGGER 0x00000004
/* [0x8]: REG Monitor and FMC status control register */
#define WB_FMC_250M_4CH_CSR_REG_MONITOR 0x00000008
/* [0xc]: REG Clock distribution control register */
#define WB_FMC_250M_4CH_CSR_REG_CLK_DISTRIB 0x0000000c
/* [0x10]: REG Global ADC Status register */
#define WB_FMC_250M_4CH_CSR_REG_ADC_STA 0x00000010
/* [0x14]: REG Global ADC Control register */
#define WB_FMC_250M_4CH_CSR_REG_ADC_CTL 0x00000014
/* [0x18]: REG Channel 0 status register */
#define WB_FMC_250M_4CH_CSR_REG_CH0_STA 0x00000018
/* [0x1c]: REG Channel 0 fine delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH0_FN_DLY 0x0000001c
/* [0x20]: REG Channel 0 coarse delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH0_CS_DLY 0x00000020
/* [0x24]: REG Channel 1 status register */
#define WB_FMC_250M_4CH_CSR_REG_CH1_STA 0x00000024
/* [0x28]: REG Channel 1 fine delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH1_FN_DLY 0x00000028
/* [0x2c]: REG Channel 1 coarse delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH1_CS_DLY 0x0000002c
/* [0x30]: REG Channel 2 status register */
#define WB_FMC_250M_4CH_CSR_REG_CH2_STA 0x00000030
/* [0x34]: REG Channel 2 fine delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH2_FN_DLY 0x00000034
/* [0x38]: REG Channel 2 coarse delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH2_CS_DLY 0x00000038
/* [0x3c]: REG Channel 3 status register */
#define WB_FMC_250M_4CH_CSR_REG_CH3_STA 0x0000003c
/* [0x40]: REG Channel 3 fine delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH3_FN_DLY 0x00000040
/* [0x44]: REG Channel 3 coarse delay register */
#define WB_FMC_250M_4CH_CSR_REG_CH3_CS_DLY 0x00000044
#endif
