onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider testbench
add wave -noupdate /wb_acq_core_tb/c_data_max
add wave -noupdate /wb_acq_core_tb/c_wait_acquisition_done
add wave -noupdate /wb_acq_core_tb/REFCLK_FREQ
add wave -noupdate /wb_acq_core_tb/SIM_BYPASS_INIT_CAL
add wave -noupdate /wb_acq_core_tb/RST_ACT_LOW
add wave -noupdate /wb_acq_core_tb/IODELAY_GRP
add wave -noupdate /wb_acq_core_tb/nCK_PER_CLK
add wave -noupdate /wb_acq_core_tb/nCS_PER_RANK
add wave -noupdate /wb_acq_core_tb/DQS_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/BANK_WIDTH
add wave -noupdate /wb_acq_core_tb/CK_WIDTH
add wave -noupdate /wb_acq_core_tb/CKE_WIDTH
add wave -noupdate /wb_acq_core_tb/COL_WIDTH
add wave -noupdate /wb_acq_core_tb/CS_WIDTH
add wave -noupdate /wb_acq_core_tb/DM_WIDTH
add wave -noupdate /wb_acq_core_tb/DQ_WIDTH
add wave -noupdate /wb_acq_core_tb/DQS_WIDTH
add wave -noupdate /wb_acq_core_tb/ROW_WIDTH
add wave -noupdate /wb_acq_core_tb/BURST_MODE
add wave -noupdate /wb_acq_core_tb/ADDR_CMD_MODE
add wave -noupdate /wb_acq_core_tb/ORDERING
add wave -noupdate /wb_acq_core_tb/RTT_NOM
add wave -noupdate /wb_acq_core_tb/RTT_WR
add wave -noupdate /wb_acq_core_tb/OUTPUT_DRV
add wave -noupdate /wb_acq_core_tb/REG_CTRL
add wave -noupdate /wb_acq_core_tb/DIVCLK_DIVIDE
add wave -noupdate /wb_acq_core_tb/tCK
add wave -noupdate /wb_acq_core_tb/DEBUG_PORT
add wave -noupdate /wb_acq_core_tb/tPRDI
add wave -noupdate /wb_acq_core_tb/tREFI
add wave -noupdate /wb_acq_core_tb/tZQI
add wave -noupdate /wb_acq_core_tb/ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/STARVE_LIMIT
add wave -noupdate /wb_acq_core_tb/TCQ
add wave -noupdate /wb_acq_core_tb/ECC
add wave -noupdate /wb_acq_core_tb/ECC_TEST
add wave -noupdate /wb_acq_core_tb/TPROP_DQS
add wave -noupdate /wb_acq_core_tb/TPROP_DQS_RD
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_CTRL
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_DATA
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_DATA_RD
add wave -noupdate /wb_acq_core_tb/MEMORY_WIDTH
add wave -noupdate /wb_acq_core_tb/NUM_COMP
add wave -noupdate /wb_acq_core_tb/CLK_PERIOD
add wave -noupdate /wb_acq_core_tb/REFCLK_HALF_PERIOD
add wave -noupdate /wb_acq_core_tb/DRAM_DEVICE
add wave -noupdate /wb_acq_core_tb/VT_ENABLE
add wave -noupdate /wb_acq_core_tb/VT_RATE
add wave -noupdate /wb_acq_core_tb/VT_UPDATE_INTERVAL
add wave -noupdate /wb_acq_core_tb/VT_MAX
add wave -noupdate /wb_acq_core_tb/SYSCLK_PERIOD
add wave -noupdate /wb_acq_core_tb/DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/PAYLOAD_WIDTH
add wave -noupdate /wb_acq_core_tb/c_n_shots_width
add wave -noupdate /wb_acq_core_tb/c_n_pre_samples_width
add wave -noupdate /wb_acq_core_tb/c_n_post_samples_width
add wave -noupdate /wb_acq_core_tb/c_n_chan
add wave -noupdate /wb_acq_core_tb/c_n_width64
add wave -noupdate /wb_acq_core_tb/c_n_width128
add wave -noupdate /wb_acq_core_tb/ACQ_ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/ACQ_DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/DATA_CHECK_FIFO_SIZE
add wave -noupdate /wb_acq_core_tb/ACQ_FIFO_SIZE
add wave -noupdate /wb_acq_core_tb/data_test_low
add wave -noupdate /wb_acq_core_tb/data_test_high
add wave -noupdate /wb_acq_core_tb/data_test_dvalid
add wave -noupdate /wb_acq_core_tb/data_test_dvalid_t
add wave -noupdate /wb_acq_core_tb/data_test_trig
add wave -noupdate /wb_acq_core_tb/data_ext_stall_threshold
add wave -noupdate /wb_acq_core_tb/data_ext_rdy_threshold
add wave -noupdate /wb_acq_core_tb/data_valid_threshold
add wave -noupdate /wb_acq_core_tb/data_gen_start
add wave -noupdate /wb_acq_core_tb/test_in_progress
add wave -noupdate /wb_acq_core_tb/stop_on_error
add wave -noupdate /wb_acq_core_tb/test_id
add wave -noupdate /wb_acq_core_tb/n_shots
add wave -noupdate /wb_acq_core_tb/pre_trig_samples
add wave -noupdate /wb_acq_core_tb/post_trig_samples
add wave -noupdate /wb_acq_core_tb/ddr3_start_addr
add wave -noupdate /wb_acq_core_tb/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/skip_trig
add wave -noupdate /wb_acq_core_tb/wait_finish
add wave -noupdate /wb_acq_core_tb/data_valid_prob
add wave -noupdate /wb_acq_core_tb/min_wait_gnt
add wave -noupdate /wb_acq_core_tb/max_wait_gnt
add wave -noupdate /wb_acq_core_tb/min_wait_gnt_l
add wave -noupdate /wb_acq_core_tb/max_wait_gnt_l
add wave -noupdate /wb_acq_core_tb/acq_core_fsm_ctl_reg
add wave -noupdate /wb_acq_core_tb/acq_core_fsm_sta_reg
add wave -noupdate /wb_acq_core_tb/error
add wave -noupdate /wb_acq_core_tb/phy_init_done
add wave -noupdate /wb_acq_core_tb/ddr3_parity
add wave -noupdate /wb_acq_core_tb/ddr3_reset_n
add wave -noupdate /wb_acq_core_tb/ddr3_dq_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_addr_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ba_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ras_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cas_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_we_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cs_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_odt_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cke_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dm_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_p_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ck_p_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ck_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dq_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_addr_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ba_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ras_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cas_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_we_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cs_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_odt_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cke_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dm_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dm_sdram_tmp
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_p_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ck_p_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ck_n_sdram
add wave -noupdate /wb_acq_core_tb/init_calib_complete
add wave -noupdate /wb_acq_core_tb/tg_compare_error
add wave -noupdate /wb_acq_core_tb/ddr_sys_clk_i
add wave -noupdate /wb_acq_core_tb/clk_ref_i
add wave -noupdate /wb_acq_core_tb/ext_dout
add wave -noupdate /wb_acq_core_tb/ext_addr
add wave -noupdate /wb_acq_core_tb/ext_valid
add wave -noupdate /wb_acq_core_tb/ext_sof
add wave -noupdate /wb_acq_core_tb/ext_eof
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_wren
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_data
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_mask
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_end
add wave -noupdate /wb_acq_core_tb/ui_app_addr
add wave -noupdate /wb_acq_core_tb/ui_app_cmd
add wave -noupdate /wb_acq_core_tb/ui_app_en
add wave -noupdate /wb_acq_core_tb/ui_app_rdy
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_rdy
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data_end
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data_valid
add wave -noupdate /wb_acq_core_tb/ui_clk_sync_rst
add wave -noupdate /wb_acq_core_tb/ui_clk_sync_rst_n
add wave -noupdate /wb_acq_core_tb/ui_clk
add wave -noupdate /wb_acq_core_tb/ui_phy_init_done
add wave -noupdate /wb_acq_core_tb/ui_app_req
add wave -noupdate /wb_acq_core_tb/ui_app_gnt
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_data
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_addr
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_valid
add wave -noupdate /wb_acq_core_tb/chk_data_err
add wave -noupdate /wb_acq_core_tb/chk_data_err_cnt
add wave -noupdate /wb_acq_core_tb/chk_addr_err
add wave -noupdate /wb_acq_core_tb/chk_addr_err_cnt
add wave -noupdate /wb_acq_core_tb/chk_end
add wave -noupdate /wb_acq_core_tb/chk_pass
add wave -noupdate /wb_acq_core_tb/sys_clk
add wave -noupdate /wb_acq_core_tb/sys_rstn
add wave -noupdate /wb_acq_core_tb/sys_rst
add wave -noupdate /wb_acq_core_tb/adc_clk
add wave -noupdate /wb_acq_core_tb/adc_rstn
add wave -noupdate /wb_acq_core_tb/clk_200mhz
add wave -noupdate /wb_acq_core_tb/clk200mhz_rstn
add wave -noupdate /wb_acq_core_tb/ddr3_sys_clk
add wave -noupdate /wb_acq_core_tb/ddr3_sys_rstn
add wave -noupdate /wb_acq_core_tb/clk_ref
add wave -noupdate /wb_acq_core_tb/sda
add wave -noupdate /wb_acq_core_tb/scl
add wave -noupdate /wb_acq_core_tb/ext_dreq
add wave -noupdate /wb_acq_core_tb/ext_stall
add wave -noupdate /wb_acq_core_tb/sys_rst_n
add wave -noupdate -divider wb_acq_core_plain
add wave -noupdate /wb_acq_core_tb/dut/g_interface_mode
add wave -noupdate /wb_acq_core_tb/dut/g_address_granularity
add wave -noupdate /wb_acq_core_tb/dut/g_acq_addr_width
add wave -noupdate /wb_acq_core_tb/dut/g_acq_num_channels
add wave -noupdate /wb_acq_core_tb/dut/g_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/g_ddr_dq_width
add wave -noupdate /wb_acq_core_tb/dut/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/g_multishot_ram_size
add wave -noupdate /wb_acq_core_tb/dut/g_fifo_fc_size
add wave -noupdate /wb_acq_core_tb/dut/g_sim_readback
add wave -noupdate /wb_acq_core_tb/dut/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/sys_clk_i
add wave -noupdate /wb_acq_core_tb/dut/sys_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/wb_adr_i
add wave -noupdate /wb_acq_core_tb/dut/wb_dat_i
add wave -noupdate /wb_acq_core_tb/dut/wb_dat_o
add wave -noupdate /wb_acq_core_tb/dut/wb_sel_i
add wave -noupdate /wb_acq_core_tb/dut/wb_we_i
add wave -noupdate /wb_acq_core_tb/dut/wb_cyc_i
add wave -noupdate /wb_acq_core_tb/dut/wb_stb_i
add wave -noupdate /wb_acq_core_tb/dut/wb_ack_o
add wave -noupdate /wb_acq_core_tb/dut/wb_err_o
add wave -noupdate /wb_acq_core_tb/dut/wb_rty_o
add wave -noupdate /wb_acq_core_tb/dut/wb_stall_o
add wave -noupdate /wb_acq_core_tb/dut/acq_val_low_i
add wave -noupdate /wb_acq_core_tb/dut/acq_val_high_i
add wave -noupdate /wb_acq_core_tb/dut/acq_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/dpram_dout_o
add wave -noupdate /wb_acq_core_tb/dut/dpram_valid_o
add wave -noupdate /wb_acq_core_tb/dut/ext_dout_o
add wave -noupdate /wb_acq_core_tb/dut/ext_valid_o
add wave -noupdate /wb_acq_core_tb/dut/ext_addr_o
add wave -noupdate /wb_acq_core_tb/dut/ext_sof_o
add wave -noupdate /wb_acq_core_tb/dut/ext_eof_o
add wave -noupdate /wb_acq_core_tb/dut/ext_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/ext_stall_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_data_o
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_addr_o
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_valid_o
add wave -noupdate /wb_acq_core_tb/dut/acq_val_low_array
add wave -noupdate /wb_acq_core_tb/dut/acq_val_high_array
add wave -noupdate /wb_acq_core_tb/dut/acq_dvalid_array
add wave -noupdate /wb_acq_core_tb/dut/acq_trig_array
add wave -noupdate -divider wb_acq_core
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_interface_mode
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_address_granularity
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_num_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_dq_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_multishot_ram_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_fifo_fc_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_sim_readback
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sys_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sys_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_adr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_dat_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_dat_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_sel_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_we_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_cyc_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_stb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_ack_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_err_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_rty_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_stall_o
add wave -noupdate -childformat {{/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0) -radix hexadecimal -childformat {{/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(63) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(62) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(61) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(60) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(59) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(58) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(57) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(56) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(55) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(54) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(53) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(52) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(51) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(50) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(49) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(48) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(47) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(46) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(45) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(44) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(43) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(42) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(41) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(40) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(39) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(38) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(37) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(36) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(35) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(34) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(33) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(32) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(31) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(30) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(29) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(28) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(27) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(26) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(25) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(24) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(23) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(22) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(21) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(20) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(19) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(18) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(17) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(16) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(15) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(14) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(13) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(12) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(11) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(10) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(9) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(8) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(7) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(6) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(5) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(4) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(3) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(2) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(1) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(0) -radix hexadecimal}}}} -expand -subitemconfig {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0) {-height 17 -radix hexadecimal -childformat {{/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(63) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(62) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(61) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(60) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(59) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(58) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(57) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(56) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(55) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(54) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(53) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(52) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(51) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(50) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(49) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(48) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(47) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(46) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(45) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(44) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(43) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(42) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(41) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(40) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(39) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(38) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(37) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(36) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(35) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(34) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(33) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(32) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(31) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(30) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(29) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(28) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(27) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(26) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(25) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(24) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(23) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(22) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(21) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(20) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(19) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(18) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(17) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(16) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(15) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(14) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(13) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(12) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(11) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(10) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(9) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(8) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(7) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(6) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(5) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(4) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(3) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(2) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(1) -radix hexadecimal} {/wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(0) -radix hexadecimal}}} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(63) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(62) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(61) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(60) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(59) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(58) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(57) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(56) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(55) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(54) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(53) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(52) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(51) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(50) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(49) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(48) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(47) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(46) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(45) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(44) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(43) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(42) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(41) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(40) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(39) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(38) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(37) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(36) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(35) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(34) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(33) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(32) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(31) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(30) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(29) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(28) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(27) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(26) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(25) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(24) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(23) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(22) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(21) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(20) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(19) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(18) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(17) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(16) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(15) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(14) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(13) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(12) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(11) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(10) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(9) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(8) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(7) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(6) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(5) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(4) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(3) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(2) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(1) {-height 17 -radix hexadecimal} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i(0)(0) {-height 17 -radix hexadecimal}} /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i
add wave -noupdate -expand /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_high_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_sof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_eof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/regs_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/regs_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_slv_adp_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_slv_adp_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/resized_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_trig_a
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_over_thres
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_over_thres_d
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_thres
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_pol
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_delay
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_delay_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_d
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_align
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_fsm_state
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_start
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_start_sync_ext
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_now
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_stop
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_end
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_pre_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_wait_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_post_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_data_marsh
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_dvalid_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/samples_wr_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/pre_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/post_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_nb_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_single_shot
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_start_addr_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_start_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_pre_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_wait_trig_skip_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_post_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/samples_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_decr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/multishot_buffer_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_acq_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_post_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addrb_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_req_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_full_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_sof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_eof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_wr_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_wr_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sim_in_rb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_rb_lmt_rb_rst
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_rst_n
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_rb_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_p_fs
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_cmd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_gnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_cmd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_gnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/test_data_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_samples_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_dpram_depth
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_periph_addr_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_data_width
add wave -noupdate -divider acq_fsm
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_start_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_now_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_stop_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/pre_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/post_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/samples_cnt_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_single_shot_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_pre_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_wait_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_post_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_pre_trig_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_wait_trig_skip_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_post_trig_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_fsm_state_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/shots_decr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/multishot_buffer_sel_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/samples_wr_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_fsm_state
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_start
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_stop
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_end
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_end_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_pre_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_wait_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/acq_in_post_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/samples_wr_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/pre_trig_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/pre_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/wait_trig_skip_r
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/wait_trig_skip_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/post_trig_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/post_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/samples_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/shots_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/shots_decr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fsm/single_shot
add wave -noupdate -divider multishot_dpram
add wave -noupdate -divider fc_fifo
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/g_fifo_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/g_fc_pipe_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/dpram_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/dpram_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pt_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pt_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pt_wr_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/req_rst_trans_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/passthrough_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/buffer_sel_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_full_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_sof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_eof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_dreq_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_stall_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_din
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_we
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_we_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_we_en_r
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_wr_count
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_data_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_oob_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_valid_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_rd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_rd_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_valid_fwft
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_last_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_first_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pl_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pl_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pl_pkt_sent
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/ext_stall_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_pkt_sent
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_data_out_pnd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_data_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_data_oob_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_dvalid_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pre_output_counter_wr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/output_counter_rd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_rd_empty
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_wr_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_sof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_eof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fc_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/req_rst_trans_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/rst_trans_fs_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/rst_trans_ext_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/pl_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/acq_cnt_rst_n
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_in_valid_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_in_valid_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_out_pend_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_pkt_sent_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_pkt_sent_ct_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_pkt_sent_ct_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/shots_sent_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/shots_sent_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_all_trans_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/fifo_fc_all_trans_done_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_fc_fifo/c_pipe_size
add wave -noupdate -divider fc_source
add wave -noupdate -divider ddr3_iface
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_acq_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_acq_num_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_ddr_dq_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_din_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_addr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_sof_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_eof_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fifo_fc_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/wr_start_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/wr_init_addr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_rst_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_curr_chan_id_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_curr_chan_id
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_valid_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_valid_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_stall_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_dreq_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_stall_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/fc_dreq_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/valid_trans_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/valid_trans_app_d0
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/valid_trans_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/cnt_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/wr_init_addr_alig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_stall_d0
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_dreq_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_stall_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_pkt_sent_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_dreq_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_stall_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_pkt_sent_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/pl_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_data_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt_min
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt_min_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt_min_ovf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt_min_ovf_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_addr_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_valid_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_mask_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_data_mask_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_rdy_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_rdy_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/ddr_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/acq_cnt_rst_n
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_acq_chan_slice
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_fc_payload_ratio
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_fc_payload_ratio_log2
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_payload_ratio_2
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_payload_ratio_4
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_payload_ratio_8
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_max_ddr_payload_ratio_log2
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_mask_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_addr_ddr_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_pkt_size_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_pipe_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_addr_cnt_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ui_cmd_write
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ui_cmd_read
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_mask_low
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_mask_high
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_data_low
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_data_high
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/cmp_acq_ddr3_iface/c_ddr_align_shift
add wave -noupdate -divider ddr3_write_cpm_acq_cnt
add wave -noupdate -divider fc_source_ddr3
add wave -noupdate -divider fc_ddr3_readback
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_interface_mode
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_address_granularity
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_num_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_dq_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_multishot_ram_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_fifo_fc_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/g_sim_readback
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sys_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sys_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_adr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_dat_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_dat_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_sel_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_we_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_cyc_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_stb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_ack_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_err_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_rty_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_low_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_val_high_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_sof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_eof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/regs_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/regs_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_slv_adp_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/wb_slv_adp_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/resized_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_trig_a
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_over_thres
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_over_thres_d
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/int_trig_thres
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_pol
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/hw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_delay
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_delay_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_d
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_align
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_fsm_state
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_start
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_start_sync_ext
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_now
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_stop
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_end
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_pre_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_wait_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_in_post_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_data_marsh
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_trig_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_dvalid_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/samples_wr_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/pre_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/post_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_nb_c
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_single_shot
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_start_addr_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_start_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_pre_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_wait_trig_skip_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_post_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/samples_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/shots_decr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/multishot_buffer_sel
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_acq_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addra_post_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_addrb_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dpram_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_req_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/fifo_fc_full_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_sof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_eof
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ext_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_wr_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_wr_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/sim_in_rb
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_rb_lmt_rb_rst
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/acq_ddr3_rst_n
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/dbg_ddr_rb_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_rb_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ddr3_all_trans_done_p_fs
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_cmd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_rb_gnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_cmd
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/ui_app_wdf_gnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/test_data_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/trig_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_channels
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_samples_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_dpram_depth
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_periph_addr_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_wb_acq_core/c_acq_data_width
add wave -noupdate -divider read_ddr3_cnt_recv
add wave -noupdate -divider data_checker
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_data_width
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_addr_width
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_fifo_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/ext_clk_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_din_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_addr_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_din_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_addr_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_data_err_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_data_err_cnt_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_end_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_pass_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_din
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_we
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_dout
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_rd
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_empty
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_full
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_din
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_we
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_dout
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_rd
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_empty
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_full
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_in_progress
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_en
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_done_p
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_done_l
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_match
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err_r
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err_cnt
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_addr_lsb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_addr_msb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_data_lsb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_data_msb
add wave -noupdate -divider ddr_v3
add wave -noupdate -divider ddr_v6_ui_top
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/COL_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CS_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/nCS_PER_RANK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CKE_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_BUF_ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQ_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQ_PER_DM
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DM_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQ_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQS_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQS_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DRAM_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ECC
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ECC_TEST
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PAYLOAD_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ECC_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MC_ERR_ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MEM_ADDR_ORDER
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/nBANK_MACHS
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RANKS
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ODT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ROW_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/USE_CS_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/USE_DM_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/USE_ODT_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PHY_CONTROL_MASTER_BANK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MEM_DENSITY
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MEM_SPEEDGRADE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MEM_DEVICE_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/AL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/nAL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BURST_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BURST_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CWL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/OUTPUT_DRV
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RTT_NOM
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RTT_WR
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ADDR_CMD_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/REG_CTRL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CA_MIRROR
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKIN_PERIOD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKFBOUT_MULT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DIVCLK_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKOUT0_PHASE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKOUT0_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKOUT1_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKOUT2_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CLKOUT3_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tCKE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tFAW
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tPRDI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRAS
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRCD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tREFI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRFC
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRRD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tRTP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tWTR
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tZQI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tZQCS
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SIM_BYPASS_INIT_CAL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SIMULATION
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BYTE_LANES_B0
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BYTE_LANES_B1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BYTE_LANES_B2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BYTE_LANES_B3
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BYTE_LANES_B4
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_CTL_B0
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_CTL_B1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_CTL_B2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_CTL_B3
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_CTL_B4
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PHY_0_BITLANES
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PHY_1_BITLANES
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PHY_2_BITLANES
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CK_BYTE_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ADDR_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BANK_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CAS_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CKE_ODT_BYTE_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CKE_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ODT_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CS_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/PARITY_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RAS_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/WE_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DQS_BYTE_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA0_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA1_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA2_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA3_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA4_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA5_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA6_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA7_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA8_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA9_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA10_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA11_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA12_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA13_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA14_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA15_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA16_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA17_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MASK0_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/MASK1_MAP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SLOT_0_CONFIG
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SLOT_1_CONFIG
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/IODELAY_HP_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/IBUF_LPWR_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_IO_IDLE_PWRDWN
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BANK_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DATA_IO_PRIM_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CKE_ODT_AUX
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/USER_REFRESH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/WRLVL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ORDERING
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CALIB_ROW_ADD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CALIB_COL_ADD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CALIB_BA_ADD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/TCQ
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/IODELAY_GRP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SYSCLK_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/REFCLK_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/SYS_RST_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CMD_PIPE_PLUS1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DRAM_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/CAL_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/STARVE_LIMIT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/REFCLK_FREQ
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DIFF_TERM_REFCLK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tCK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/nCK_PER_CLK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DIFF_TERM_SYSCLK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/DEBUG_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/TEMP_MON_CONTROL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RST_ACT_LOW
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_dq
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_dqs_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_dqs_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_ba
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_ras_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_cas_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_we_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_reset_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_ck_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_ck_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_cke
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_cs_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_dm
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_odt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sys_clk_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_cmd
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_wdf_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_wdf_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_wdf_mask
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_wdf_wren
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_rd_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_rd_data_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_rd_data_valid
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_wdf_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_sr_req
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_sr_active
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_ref_req
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_ref_ack
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_zq_req
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_zq_ack
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ui_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ui_clk_sync_rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/init_calib_complete
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sys_rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/bank_mach_next
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk_ref
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/iodelay_ctrl_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk_ref_in
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sys_rst_o
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/freq_refclk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/mem_refclk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/pll_locked
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sync_pulse
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ref_dll_lock
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/rst_phaser_ref
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/app_ecc_multiple_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ddr3_parity
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/init_calib_complete_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sys_clk_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/sys_clk_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/mmcm_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk_ref_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk_ref_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/clk_ref_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/device_temp
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/device_temp_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_idel_down_all
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_idel_down_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_idel_up_all
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_idel_up_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_sel_all_idel_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_sel_idel_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_po_f_stg23_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_sel_pi_incdec
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_sel_po_incdec
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_byte_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_f_inc
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_po_f_inc
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_f_dec
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_po_f_dec
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_counter_read_val
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_po_counter_read_val
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_cpt_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_dq_idelay_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_calib_top
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_cpt_first_edge_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_cpt_second_edge_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rd_data_offset
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_phy_rdlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_phy_wrcal
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_final_po_fine_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_final_po_coarse_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_phy_wrlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_phy_init
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_prbs_rdlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_dqs_found_cal
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_phaselock_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_phaselocked_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_phaselock_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_dqsfound_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_dqsfound_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_dqsfound_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrcal_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrcal_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrcal_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_dqs_found_lanes_phy4lanes
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_pi_phase_locked_phy4lanes
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_oclkdelay_calib_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_oclkdelay_calib_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_phy_oclkdelay_cal
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_oclkdelay_rd_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rd_data_edge_detect
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rddata
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rddata_valid
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rdlvl_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rdlvl_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rdlvl_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrlvl_fine_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrlvl_coarse_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_tap_cnt_during_wrlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wl_edge_detect_valid
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrlvl_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrlvl_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_wrlvl_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rddata_r
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_rddata_valid_r
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/ocal_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_dqs
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_bit
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/rd_data_edge_detect_r
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/wl_po_fine_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/wl_po_coarse_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_calib_rd_data_offset_1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_calib_rd_data_offset_2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_data_offset
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_data_offset_1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/dbg_data_offset_2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/all_zeros
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/BM_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/RANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/APP_DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/APP_MASK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/TEMP_MON_EN
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/tTEMPSAMPLE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_core/XADC_CLK_PERIOD
add wave -noupdate -divider ddr3_model_3
add wave -noupdate -divider ddr3_model_2
add wave -noupdate -divider ddr3_model_1
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/odt}
add wave -noupdate -divider ddr3_model_0
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/odt}
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/cmp_exp_data_fifo/g_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/cmp_act_data_fifo/g_size
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {103914959000 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 234
configure wave -valuecolwidth 547
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {35426257217 fs}
