---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for Control and status register for the MLVDS trigger
---------------------------------------------------------------------------------------
-- File           : wb_slave_trigger_regs_pkg.vhd
-- Author         : auto-generated by wbgen2 from wb_trigger.wb
-- Created        : Fri May  6 13:58:12 2016
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE wb_trigger.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package wb_trig_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_wb_trig_in_registers is record
    ch0_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch0_count_transm_i                       : std_logic_vector(15 downto 0);
    ch1_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch1_count_transm_i                       : std_logic_vector(15 downto 0);
    ch2_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch2_count_transm_i                       : std_logic_vector(15 downto 0);
    ch3_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch3_count_transm_i                       : std_logic_vector(15 downto 0);
    ch4_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch4_count_transm_i                       : std_logic_vector(15 downto 0);
    ch5_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch5_count_transm_i                       : std_logic_vector(15 downto 0);
    ch6_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch6_count_transm_i                       : std_logic_vector(15 downto 0);
    ch7_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch7_count_transm_i                       : std_logic_vector(15 downto 0);
    ch8_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch8_count_transm_i                       : std_logic_vector(15 downto 0);
    ch9_count_rcv_i                          : std_logic_vector(15 downto 0);
    ch9_count_transm_i                       : std_logic_vector(15 downto 0);
    ch10_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch10_count_transm_i                      : std_logic_vector(15 downto 0);
    ch11_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch11_count_transm_i                      : std_logic_vector(15 downto 0);
    ch12_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch12_count_transm_i                      : std_logic_vector(15 downto 0);
    ch13_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch13_count_transm_i                      : std_logic_vector(15 downto 0);
    ch14_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch14_count_transm_i                      : std_logic_vector(15 downto 0);
    ch15_count_rcv_i                         : std_logic_vector(15 downto 0);
    ch15_count_transm_i                      : std_logic_vector(15 downto 0);
    end record;
  
  constant c_wb_trig_in_registers_init_value: t_wb_trig_in_registers := (
    ch0_count_rcv_i => (others => '0'),
    ch0_count_transm_i => (others => '0'),
    ch1_count_rcv_i => (others => '0'),
    ch1_count_transm_i => (others => '0'),
    ch2_count_rcv_i => (others => '0'),
    ch2_count_transm_i => (others => '0'),
    ch3_count_rcv_i => (others => '0'),
    ch3_count_transm_i => (others => '0'),
    ch4_count_rcv_i => (others => '0'),
    ch4_count_transm_i => (others => '0'),
    ch5_count_rcv_i => (others => '0'),
    ch5_count_transm_i => (others => '0'),
    ch6_count_rcv_i => (others => '0'),
    ch6_count_transm_i => (others => '0'),
    ch7_count_rcv_i => (others => '0'),
    ch7_count_transm_i => (others => '0'),
    ch8_count_rcv_i => (others => '0'),
    ch8_count_transm_i => (others => '0'),
    ch9_count_rcv_i => (others => '0'),
    ch9_count_transm_i => (others => '0'),
    ch10_count_rcv_i => (others => '0'),
    ch10_count_transm_i => (others => '0'),
    ch11_count_rcv_i => (others => '0'),
    ch11_count_transm_i => (others => '0'),
    ch12_count_rcv_i => (others => '0'),
    ch12_count_transm_i => (others => '0'),
    ch13_count_rcv_i => (others => '0'),
    ch13_count_transm_i => (others => '0'),
    ch14_count_rcv_i => (others => '0'),
    ch14_count_transm_i => (others => '0'),
    ch15_count_rcv_i => (others => '0'),
    ch15_count_transm_i => (others => '0')
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_wb_trig_out_registers is record
      ch0_ctl_dir_o                            : std_logic;
      ch0_ctl_rcv_count_rst_o                  : std_logic;
      ch0_ctl_transm_count_rst_o               : std_logic;
      ch0_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch0_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch0_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch0_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch1_ctl_dir_o                            : std_logic;
      ch1_ctl_rcv_count_rst_o                  : std_logic;
      ch1_ctl_transm_count_rst_o               : std_logic;
      ch1_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch1_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch1_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch1_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch2_ctl_dir_o                            : std_logic;
      ch2_ctl_rcv_count_rst_o                  : std_logic;
      ch2_ctl_transm_count_rst_o               : std_logic;
      ch2_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch2_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch2_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch2_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch3_ctl_dir_o                            : std_logic;
      ch3_ctl_rcv_count_rst_o                  : std_logic;
      ch3_ctl_transm_count_rst_o               : std_logic;
      ch3_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch3_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch3_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch3_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch4_ctl_dir_o                            : std_logic;
      ch4_ctl_rcv_count_rst_o                  : std_logic;
      ch4_ctl_transm_count_rst_o               : std_logic;
      ch4_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch4_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch4_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch4_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch5_ctl_dir_o                            : std_logic;
      ch5_ctl_rcv_count_rst_o                  : std_logic;
      ch5_ctl_transm_count_rst_o               : std_logic;
      ch5_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch5_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch5_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch5_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch6_ctl_dir_o                            : std_logic;
      ch6_ctl_rcv_count_rst_o                  : std_logic;
      ch6_ctl_transm_count_rst_o               : std_logic;
      ch6_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch6_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch6_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch6_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch7_ctl_dir_o                            : std_logic;
      ch7_ctl_rcv_count_rst_o                  : std_logic;
      ch7_ctl_transm_count_rst_o               : std_logic;
      ch7_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch7_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch7_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch7_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch8_ctl_dir_o                            : std_logic;
      ch8_ctl_rcv_count_rst_o                  : std_logic;
      ch8_ctl_transm_count_rst_o               : std_logic;
      ch8_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch8_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch8_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch8_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch9_ctl_dir_o                            : std_logic;
      ch9_ctl_rcv_count_rst_o                  : std_logic;
      ch9_ctl_transm_count_rst_o               : std_logic;
      ch9_ctl_rcv_in_sel_o                     : std_logic_vector(7 downto 0);
      ch9_ctl_transm_out_sel_o                 : std_logic_vector(7 downto 0);
      ch9_cfg_rcv_len_o                        : std_logic_vector(7 downto 0);
      ch9_cfg_transm_len_o                     : std_logic_vector(7 downto 0);
      ch10_ctl_dir_o                           : std_logic;
      ch10_ctl_rcv_count_rst_o                 : std_logic;
      ch10_ctl_transm_count_rst_o              : std_logic;
      ch10_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch10_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch10_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch10_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      ch11_ctl_dir_o                           : std_logic;
      ch11_ctl_rcv_count_rst_o                 : std_logic;
      ch11_ctl_transm_count_rst_o              : std_logic;
      ch11_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch11_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch11_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch11_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      ch12_ctl_dir_o                           : std_logic;
      ch12_ctl_rcv_count_rst_o                 : std_logic;
      ch12_ctl_transm_count_rst_o              : std_logic;
      ch12_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch12_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch12_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch12_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      ch13_ctl_dir_o                           : std_logic;
      ch13_ctl_rcv_count_rst_o                 : std_logic;
      ch13_ctl_transm_count_rst_o              : std_logic;
      ch13_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch13_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch13_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch13_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      ch14_ctl_dir_o                           : std_logic;
      ch14_ctl_rcv_count_rst_o                 : std_logic;
      ch14_ctl_transm_count_rst_o              : std_logic;
      ch14_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch14_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch14_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch14_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      ch15_ctl_dir_o                           : std_logic;
      ch15_ctl_rcv_count_rst_o                 : std_logic;
      ch15_ctl_transm_count_rst_o              : std_logic;
      ch15_ctl_rcv_in_sel_o                    : std_logic_vector(7 downto 0);
      ch15_ctl_transm_out_sel_o                : std_logic_vector(7 downto 0);
      ch15_cfg_rcv_len_o                       : std_logic_vector(7 downto 0);
      ch15_cfg_transm_len_o                    : std_logic_vector(7 downto 0);
      end record;
    
    constant c_wb_trig_out_registers_init_value: t_wb_trig_out_registers := (
      ch0_ctl_dir_o => '0',
      ch0_ctl_rcv_count_rst_o => '0',
      ch0_ctl_transm_count_rst_o => '0',
      ch0_ctl_rcv_in_sel_o => (others => '0'),
      ch0_ctl_transm_out_sel_o => (others => '0'),
      ch0_cfg_rcv_len_o => (others => '0'),
      ch0_cfg_transm_len_o => (others => '0'),
      ch1_ctl_dir_o => '0',
      ch1_ctl_rcv_count_rst_o => '0',
      ch1_ctl_transm_count_rst_o => '0',
      ch1_ctl_rcv_in_sel_o => (others => '0'),
      ch1_ctl_transm_out_sel_o => (others => '0'),
      ch1_cfg_rcv_len_o => (others => '0'),
      ch1_cfg_transm_len_o => (others => '0'),
      ch2_ctl_dir_o => '0',
      ch2_ctl_rcv_count_rst_o => '0',
      ch2_ctl_transm_count_rst_o => '0',
      ch2_ctl_rcv_in_sel_o => (others => '0'),
      ch2_ctl_transm_out_sel_o => (others => '0'),
      ch2_cfg_rcv_len_o => (others => '0'),
      ch2_cfg_transm_len_o => (others => '0'),
      ch3_ctl_dir_o => '0',
      ch3_ctl_rcv_count_rst_o => '0',
      ch3_ctl_transm_count_rst_o => '0',
      ch3_ctl_rcv_in_sel_o => (others => '0'),
      ch3_ctl_transm_out_sel_o => (others => '0'),
      ch3_cfg_rcv_len_o => (others => '0'),
      ch3_cfg_transm_len_o => (others => '0'),
      ch4_ctl_dir_o => '0',
      ch4_ctl_rcv_count_rst_o => '0',
      ch4_ctl_transm_count_rst_o => '0',
      ch4_ctl_rcv_in_sel_o => (others => '0'),
      ch4_ctl_transm_out_sel_o => (others => '0'),
      ch4_cfg_rcv_len_o => (others => '0'),
      ch4_cfg_transm_len_o => (others => '0'),
      ch5_ctl_dir_o => '0',
      ch5_ctl_rcv_count_rst_o => '0',
      ch5_ctl_transm_count_rst_o => '0',
      ch5_ctl_rcv_in_sel_o => (others => '0'),
      ch5_ctl_transm_out_sel_o => (others => '0'),
      ch5_cfg_rcv_len_o => (others => '0'),
      ch5_cfg_transm_len_o => (others => '0'),
      ch6_ctl_dir_o => '0',
      ch6_ctl_rcv_count_rst_o => '0',
      ch6_ctl_transm_count_rst_o => '0',
      ch6_ctl_rcv_in_sel_o => (others => '0'),
      ch6_ctl_transm_out_sel_o => (others => '0'),
      ch6_cfg_rcv_len_o => (others => '0'),
      ch6_cfg_transm_len_o => (others => '0'),
      ch7_ctl_dir_o => '0',
      ch7_ctl_rcv_count_rst_o => '0',
      ch7_ctl_transm_count_rst_o => '0',
      ch7_ctl_rcv_in_sel_o => (others => '0'),
      ch7_ctl_transm_out_sel_o => (others => '0'),
      ch7_cfg_rcv_len_o => (others => '0'),
      ch7_cfg_transm_len_o => (others => '0'),
      ch8_ctl_dir_o => '0',
      ch8_ctl_rcv_count_rst_o => '0',
      ch8_ctl_transm_count_rst_o => '0',
      ch8_ctl_rcv_in_sel_o => (others => '0'),
      ch8_ctl_transm_out_sel_o => (others => '0'),
      ch8_cfg_rcv_len_o => (others => '0'),
      ch8_cfg_transm_len_o => (others => '0'),
      ch9_ctl_dir_o => '0',
      ch9_ctl_rcv_count_rst_o => '0',
      ch9_ctl_transm_count_rst_o => '0',
      ch9_ctl_rcv_in_sel_o => (others => '0'),
      ch9_ctl_transm_out_sel_o => (others => '0'),
      ch9_cfg_rcv_len_o => (others => '0'),
      ch9_cfg_transm_len_o => (others => '0'),
      ch10_ctl_dir_o => '0',
      ch10_ctl_rcv_count_rst_o => '0',
      ch10_ctl_transm_count_rst_o => '0',
      ch10_ctl_rcv_in_sel_o => (others => '0'),
      ch10_ctl_transm_out_sel_o => (others => '0'),
      ch10_cfg_rcv_len_o => (others => '0'),
      ch10_cfg_transm_len_o => (others => '0'),
      ch11_ctl_dir_o => '0',
      ch11_ctl_rcv_count_rst_o => '0',
      ch11_ctl_transm_count_rst_o => '0',
      ch11_ctl_rcv_in_sel_o => (others => '0'),
      ch11_ctl_transm_out_sel_o => (others => '0'),
      ch11_cfg_rcv_len_o => (others => '0'),
      ch11_cfg_transm_len_o => (others => '0'),
      ch12_ctl_dir_o => '0',
      ch12_ctl_rcv_count_rst_o => '0',
      ch12_ctl_transm_count_rst_o => '0',
      ch12_ctl_rcv_in_sel_o => (others => '0'),
      ch12_ctl_transm_out_sel_o => (others => '0'),
      ch12_cfg_rcv_len_o => (others => '0'),
      ch12_cfg_transm_len_o => (others => '0'),
      ch13_ctl_dir_o => '0',
      ch13_ctl_rcv_count_rst_o => '0',
      ch13_ctl_transm_count_rst_o => '0',
      ch13_ctl_rcv_in_sel_o => (others => '0'),
      ch13_ctl_transm_out_sel_o => (others => '0'),
      ch13_cfg_rcv_len_o => (others => '0'),
      ch13_cfg_transm_len_o => (others => '0'),
      ch14_ctl_dir_o => '0',
      ch14_ctl_rcv_count_rst_o => '0',
      ch14_ctl_transm_count_rst_o => '0',
      ch14_ctl_rcv_in_sel_o => (others => '0'),
      ch14_ctl_transm_out_sel_o => (others => '0'),
      ch14_cfg_rcv_len_o => (others => '0'),
      ch14_cfg_transm_len_o => (others => '0'),
      ch15_ctl_dir_o => '0',
      ch15_ctl_rcv_count_rst_o => '0',
      ch15_ctl_transm_count_rst_o => '0',
      ch15_ctl_rcv_in_sel_o => (others => '0'),
      ch15_ctl_transm_out_sel_o => (others => '0'),
      ch15_cfg_rcv_len_o => (others => '0'),
      ch15_cfg_transm_len_o => (others => '0')
      );
    function "or" (left, right: t_wb_trig_in_registers) return t_wb_trig_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body wb_trig_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if x = '1' then
return '1';
else
return '0';
end if;
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_wb_trig_in_registers) return t_wb_trig_in_registers is
variable tmp: t_wb_trig_in_registers;
begin
tmp.ch0_count_rcv_i := f_x_to_zero(left.ch0_count_rcv_i) or f_x_to_zero(right.ch0_count_rcv_i);
tmp.ch0_count_transm_i := f_x_to_zero(left.ch0_count_transm_i) or f_x_to_zero(right.ch0_count_transm_i);
tmp.ch1_count_rcv_i := f_x_to_zero(left.ch1_count_rcv_i) or f_x_to_zero(right.ch1_count_rcv_i);
tmp.ch1_count_transm_i := f_x_to_zero(left.ch1_count_transm_i) or f_x_to_zero(right.ch1_count_transm_i);
tmp.ch2_count_rcv_i := f_x_to_zero(left.ch2_count_rcv_i) or f_x_to_zero(right.ch2_count_rcv_i);
tmp.ch2_count_transm_i := f_x_to_zero(left.ch2_count_transm_i) or f_x_to_zero(right.ch2_count_transm_i);
tmp.ch3_count_rcv_i := f_x_to_zero(left.ch3_count_rcv_i) or f_x_to_zero(right.ch3_count_rcv_i);
tmp.ch3_count_transm_i := f_x_to_zero(left.ch3_count_transm_i) or f_x_to_zero(right.ch3_count_transm_i);
tmp.ch4_count_rcv_i := f_x_to_zero(left.ch4_count_rcv_i) or f_x_to_zero(right.ch4_count_rcv_i);
tmp.ch4_count_transm_i := f_x_to_zero(left.ch4_count_transm_i) or f_x_to_zero(right.ch4_count_transm_i);
tmp.ch5_count_rcv_i := f_x_to_zero(left.ch5_count_rcv_i) or f_x_to_zero(right.ch5_count_rcv_i);
tmp.ch5_count_transm_i := f_x_to_zero(left.ch5_count_transm_i) or f_x_to_zero(right.ch5_count_transm_i);
tmp.ch6_count_rcv_i := f_x_to_zero(left.ch6_count_rcv_i) or f_x_to_zero(right.ch6_count_rcv_i);
tmp.ch6_count_transm_i := f_x_to_zero(left.ch6_count_transm_i) or f_x_to_zero(right.ch6_count_transm_i);
tmp.ch7_count_rcv_i := f_x_to_zero(left.ch7_count_rcv_i) or f_x_to_zero(right.ch7_count_rcv_i);
tmp.ch7_count_transm_i := f_x_to_zero(left.ch7_count_transm_i) or f_x_to_zero(right.ch7_count_transm_i);
tmp.ch8_count_rcv_i := f_x_to_zero(left.ch8_count_rcv_i) or f_x_to_zero(right.ch8_count_rcv_i);
tmp.ch8_count_transm_i := f_x_to_zero(left.ch8_count_transm_i) or f_x_to_zero(right.ch8_count_transm_i);
tmp.ch9_count_rcv_i := f_x_to_zero(left.ch9_count_rcv_i) or f_x_to_zero(right.ch9_count_rcv_i);
tmp.ch9_count_transm_i := f_x_to_zero(left.ch9_count_transm_i) or f_x_to_zero(right.ch9_count_transm_i);
tmp.ch10_count_rcv_i := f_x_to_zero(left.ch10_count_rcv_i) or f_x_to_zero(right.ch10_count_rcv_i);
tmp.ch10_count_transm_i := f_x_to_zero(left.ch10_count_transm_i) or f_x_to_zero(right.ch10_count_transm_i);
tmp.ch11_count_rcv_i := f_x_to_zero(left.ch11_count_rcv_i) or f_x_to_zero(right.ch11_count_rcv_i);
tmp.ch11_count_transm_i := f_x_to_zero(left.ch11_count_transm_i) or f_x_to_zero(right.ch11_count_transm_i);
tmp.ch12_count_rcv_i := f_x_to_zero(left.ch12_count_rcv_i) or f_x_to_zero(right.ch12_count_rcv_i);
tmp.ch12_count_transm_i := f_x_to_zero(left.ch12_count_transm_i) or f_x_to_zero(right.ch12_count_transm_i);
tmp.ch13_count_rcv_i := f_x_to_zero(left.ch13_count_rcv_i) or f_x_to_zero(right.ch13_count_rcv_i);
tmp.ch13_count_transm_i := f_x_to_zero(left.ch13_count_transm_i) or f_x_to_zero(right.ch13_count_transm_i);
tmp.ch14_count_rcv_i := f_x_to_zero(left.ch14_count_rcv_i) or f_x_to_zero(right.ch14_count_rcv_i);
tmp.ch14_count_transm_i := f_x_to_zero(left.ch14_count_transm_i) or f_x_to_zero(right.ch14_count_transm_i);
tmp.ch15_count_rcv_i := f_x_to_zero(left.ch15_count_rcv_i) or f_x_to_zero(right.ch15_count_rcv_i);
tmp.ch15_count_transm_i := f_x_to_zero(left.ch15_count_transm_i) or f_x_to_zero(right.ch15_count_transm_i);
return tmp;
end function;
end package body;
