files = ["wb_acq_core.vhd",
        "xwb_acq_core.vhd",
        "wb_acq_core_plain.vhd",
        "acq_fsm.vhd",
        "acq_core_pkg.vhd",
        "acq_multishot_dpram.vhd",
        "acq_fc_fifo.vhd",
        "fc_source.vhd",
        "acq_ddr3_iface.vhd",
        "acq_ddr3_read.vhd",
        "acq_cnt.vhd",
        "acq_sel_chan.vhd",
        "data_checker.vhd",
        "wbgen/acq_core_regs_pkg.vhd",
        "wbgen/acq_core_regs.vhd"
       ];
