onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider wb_orbit_intlk_tb
add wave -noupdate /wb_orbit_intlk_tb/c_ADC_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/c_DECIM_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/c_INTLK_LMT_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/sys_clk
add wave -noupdate /wb_orbit_intlk_tb/sys_rstn
add wave -noupdate /wb_orbit_intlk_tb/sys_rst
add wave -noupdate /wb_orbit_intlk_tb/intlk_en
add wave -noupdate /wb_orbit_intlk_tb/intlk_clr
add wave -noupdate /wb_orbit_intlk_tb/intlk_min_sum_en
add wave -noupdate /wb_orbit_intlk_tb/intlk_min_sum
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_en
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_clr
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_max_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_max_y
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_en
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_clr
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_max_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_max_y
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_ch0_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_ch1_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_ch2_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_ch3_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_tag
add wave -noupdate /wb_orbit_intlk_tb/adc_ds_swap_valid
add wave -noupdate /wb_orbit_intlk_tb/decim_ds_pos_x
add wave -noupdate /wb_orbit_intlk_tb/decim_ds_pos_y
add wave -noupdate /wb_orbit_intlk_tb/decim_ds_pos_q
add wave -noupdate /wb_orbit_intlk_tb/decim_ds_pos_sum
add wave -noupdate /wb_orbit_intlk_tb/decim_ds_pos_valid
add wave -noupdate /wb_orbit_intlk_tb/adc_us_ch0_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_us_ch1_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_us_ch2_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_us_ch3_swap
add wave -noupdate /wb_orbit_intlk_tb/adc_us_tag
add wave -noupdate /wb_orbit_intlk_tb/adc_us_swap_valid
add wave -noupdate /wb_orbit_intlk_tb/decim_us_pos_x
add wave -noupdate /wb_orbit_intlk_tb/decim_us_pos_y
add wave -noupdate /wb_orbit_intlk_tb/decim_us_pos_q
add wave -noupdate /wb_orbit_intlk_tb/decim_us_pos_sum
add wave -noupdate /wb_orbit_intlk_tb/decim_us_pos_valid
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_bigger_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_bigger_y
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_bigger_ltc_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_bigger_ltc_y
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_bigger
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans_ltc
add wave -noupdate /wb_orbit_intlk_tb/intlk_trans
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_bigger_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_bigger_y
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_bigger_ltc_x
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_bigger_ltc_y
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_bigger
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang_ltc
add wave -noupdate /wb_orbit_intlk_tb/intlk_ang
add wave -noupdate /wb_orbit_intlk_tb/intlk_ltc
add wave -noupdate /wb_orbit_intlk_tb/intlk
add wave -noupdate /wb_orbit_intlk_tb/test_id
add wave -noupdate /wb_orbit_intlk_tb/test_in_progress
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_en
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_min_sum_en
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_min_sum
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_trans_en
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_trans_max_x
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_trans_max_y
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_ang_en
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_ang_max_x
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_ang_max_y
add wave -noupdate /wb_orbit_intlk_tb/test_decim_ds_pos_x
add wave -noupdate /wb_orbit_intlk_tb/test_decim_ds_pos_y
add wave -noupdate /wb_orbit_intlk_tb/test_decim_ds_pos_q
add wave -noupdate /wb_orbit_intlk_tb/test_decim_ds_pos_sum
add wave -noupdate /wb_orbit_intlk_tb/test_decim_us_pos_x
add wave -noupdate /wb_orbit_intlk_tb/test_decim_us_pos_y
add wave -noupdate /wb_orbit_intlk_tb/test_decim_us_pos_q
add wave -noupdate /wb_orbit_intlk_tb/test_decim_us_pos_sum
add wave -noupdate /wb_orbit_intlk_tb/test_intlk_status
add wave -noupdate -divider DUT
add wave -noupdate /wb_orbit_intlk_tb/DUT/g_INTERFACE_MODE
add wave -noupdate /wb_orbit_intlk_tb/DUT/g_ADDRESS_GRANULARITY
add wave -noupdate /wb_orbit_intlk_tb/DUT/g_WITH_EXTRA_WB_REG
add wave -noupdate /wb_orbit_intlk_tb/DUT/g_ADC_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/g_DECIM_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/rst_n_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/clk_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/ref_rst_n_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/ref_clk_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_adr_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_dat_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_dat_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_sel_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_we_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_cyc_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_stb_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_ack_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_stall_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/fs_clk_ds_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_ch0_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_ch1_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_ch2_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_ch3_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_tag_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_ds_swap_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_ds_pos_x_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_ds_pos_y_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_ds_pos_q_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_ds_pos_sum_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_ds_pos_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/fs_clk_us_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_ch0_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_ch1_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_ch2_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_ch3_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_tag_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/adc_us_swap_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_us_pos_x_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_us_pos_y_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_us_pos_q_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_us_pos_sum_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/decim_us_pos_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_ltc_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_ltc_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_ltc_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_ltc_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_ltc_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_ltc_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ltc_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/regs_in
add wave -noupdate /wb_orbit_intlk_tb/DUT/regs_out
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_slv_adp_out
add wave -noupdate /wb_orbit_intlk_tb/DUT/wb_slv_adp_in
add wave -noupdate /wb_orbit_intlk_tb/DUT/resized_addr
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_en_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_clr_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_min_sum_en_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_min_sum_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_en_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_clr_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_max_x_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_max_y_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_en_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_clr_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_max_x_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_max_y_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_x
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_y
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_ltc_x
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger_ltc_y
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_bigger
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans_ltc
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_trans
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_x
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_y
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_ltc_x
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger_ltc_y
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_bigger
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang_ltc
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ang
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk_ltc
add wave -noupdate /wb_orbit_intlk_tb/DUT/intlk
add wave -noupdate /wb_orbit_intlk_tb/DUT/c_PERIPH_ADDR_SIZE
add wave -noupdate /wb_orbit_intlk_tb/DUT/c_INTLK_LMT_WIDTH
add wave -noupdate -divider orbit_intlk_cdc
add wave -noupdate -divider intlk_trans
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/g_ADC_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/g_DECIM_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/g_INTLK_LMT_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/fs_rst_n_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/fs_clk_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_en_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_clr_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_max_x_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_max_y_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_ch0_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_ch1_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_ch2_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_ch3_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_tag_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_ds_swap_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_ds_pos_x_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_ds_pos_y_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_ds_pos_q_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_ds_pos_sum_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_ds_pos_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_ch0_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_ch1_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_ch2_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_ch3_swap_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_tag_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_us_swap_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_us_pos_x_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_us_pos_y_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_us_pos_q_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_us_pos_sum_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_us_pos_valid_i
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_bigger_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_bigger_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_bigger_ltc_x_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_bigger_ltc_y_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_bigger_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_ltc_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_o
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_array
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_tag_array
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_valid_array
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_pos_array
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_pos_valid_array
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_max
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/intlk_trans_max_n
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_valid_and
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/adc_valid
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_pos_valid_and
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/decim_pos_valid
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_sum
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_sum_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_sum_valid
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_sum_valid_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_valid
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_n
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_bigger
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_bigger_valid
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_bigger_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_bigger_valid_reg
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_ltc_all
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_bigger_or
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_bigger
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_all
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_ltc
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk_any
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/trans_intlk
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/c_ADC_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/c_DECIM_WIDTH
add wave -noupdate /wb_orbit_intlk_tb/DUT/cmp_orbit_intlk/cmp_orbit_intlk_trans/c_INTLK_LMT_WIDTH
add wave -noupdate -divider intlk_ang
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1044545120 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 191
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1179077134 fs} {2174785414 fs}
