onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider testbench
add wave -noupdate /wb_acq_core_tb/c_data_max
add wave -noupdate /wb_acq_core_tb/c_wait_acquisition_done
add wave -noupdate /wb_acq_core_tb/REFCLK_FREQ
add wave -noupdate /wb_acq_core_tb/SIM_BYPASS_INIT_CAL
add wave -noupdate /wb_acq_core_tb/RST_ACT_LOW
add wave -noupdate /wb_acq_core_tb/IODELAY_GRP
add wave -noupdate /wb_acq_core_tb/nCK_PER_CLK
add wave -noupdate /wb_acq_core_tb/nCS_PER_RANK
add wave -noupdate /wb_acq_core_tb/DQS_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/RANK_WIDTH
add wave -noupdate /wb_acq_core_tb/BANK_WIDTH
add wave -noupdate /wb_acq_core_tb/CK_WIDTH
add wave -noupdate /wb_acq_core_tb/CKE_WIDTH
add wave -noupdate /wb_acq_core_tb/COL_WIDTH
add wave -noupdate /wb_acq_core_tb/CS_WIDTH
add wave -noupdate /wb_acq_core_tb/DM_WIDTH
add wave -noupdate /wb_acq_core_tb/DQ_WIDTH
add wave -noupdate /wb_acq_core_tb/DQS_WIDTH
add wave -noupdate /wb_acq_core_tb/ROW_WIDTH
add wave -noupdate /wb_acq_core_tb/BURST_MODE
add wave -noupdate /wb_acq_core_tb/INPUT_CLK_TYPE
add wave -noupdate /wb_acq_core_tb/BM_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/ADDR_CMD_MODE
add wave -noupdate /wb_acq_core_tb/ORDERING
add wave -noupdate /wb_acq_core_tb/RTT_NOM
add wave -noupdate /wb_acq_core_tb/RTT_WR
add wave -noupdate /wb_acq_core_tb/OUTPUT_DRV
add wave -noupdate /wb_acq_core_tb/REG_CTRL
add wave -noupdate /wb_acq_core_tb/CLKFBOUT_MULT_F
add wave -noupdate /wb_acq_core_tb/DIVCLK_DIVIDE
add wave -noupdate /wb_acq_core_tb/CLKOUT_DIVIDE
add wave -noupdate /wb_acq_core_tb/tCK
add wave -noupdate /wb_acq_core_tb/DEBUG_PORT
add wave -noupdate /wb_acq_core_tb/tPRDI
add wave -noupdate /wb_acq_core_tb/tREFI
add wave -noupdate /wb_acq_core_tb/tZQI
add wave -noupdate /wb_acq_core_tb/ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/STARVE_LIMIT
add wave -noupdate /wb_acq_core_tb/TCQ
add wave -noupdate /wb_acq_core_tb/ECC
add wave -noupdate /wb_acq_core_tb/ECC_TEST
add wave -noupdate /wb_acq_core_tb/TPROP_DQS
add wave -noupdate /wb_acq_core_tb/TPROP_DQS_RD
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_CTRL
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_DATA
add wave -noupdate /wb_acq_core_tb/TPROP_PCB_DATA_RD
add wave -noupdate /wb_acq_core_tb/MEMORY_WIDTH
add wave -noupdate /wb_acq_core_tb/NUM_COMP
add wave -noupdate /wb_acq_core_tb/CLK_PERIOD
add wave -noupdate /wb_acq_core_tb/REFCLK_HALF_PERIOD
add wave -noupdate /wb_acq_core_tb/DRAM_DEVICE
add wave -noupdate /wb_acq_core_tb/VT_ENABLE
add wave -noupdate /wb_acq_core_tb/VT_RATE
add wave -noupdate /wb_acq_core_tb/VT_UPDATE_INTERVAL
add wave -noupdate /wb_acq_core_tb/VT_MAX
add wave -noupdate /wb_acq_core_tb/SYSCLK_PERIOD
add wave -noupdate /wb_acq_core_tb/DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/PAYLOAD_WIDTH
add wave -noupdate /wb_acq_core_tb/DATA_CHECK_FIFO_SIZE
add wave -noupdate /wb_acq_core_tb/c_n_shots_width
add wave -noupdate /wb_acq_core_tb/c_n_pre_samples_width
add wave -noupdate /wb_acq_core_tb/c_n_post_samples_width
add wave -noupdate /wb_acq_core_tb/data_test
add wave -noupdate /wb_acq_core_tb/data_test_valid
add wave -noupdate /wb_acq_core_tb/data_test_valid_t
add wave -noupdate /wb_acq_core_tb/trigger_test
add wave -noupdate /wb_acq_core_tb/data_ext_stall_threshold
add wave -noupdate /wb_acq_core_tb/data_ext_rdy_threshold
add wave -noupdate /wb_acq_core_tb/data_valid_threshold
add wave -noupdate /wb_acq_core_tb/data_gen_start
add wave -noupdate /wb_acq_core_tb/test_in_progress
add wave -noupdate /wb_acq_core_tb/stop_on_error
add wave -noupdate /wb_acq_core_tb/test_id
add wave -noupdate /wb_acq_core_tb/n_shots
add wave -noupdate /wb_acq_core_tb/pre_trig_samples
add wave -noupdate /wb_acq_core_tb/post_trig_samples
add wave -noupdate /wb_acq_core_tb/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/skip_trig
add wave -noupdate /wb_acq_core_tb/wait_finish
add wave -noupdate /wb_acq_core_tb/data_valid_prob
add wave -noupdate /wb_acq_core_tb/min_wait_gnt
add wave -noupdate /wb_acq_core_tb/max_wait_gnt
add wave -noupdate /wb_acq_core_tb/acq_core_fsm_ctl_reg
add wave -noupdate /wb_acq_core_tb/acq_core_fsm_sta_reg
add wave -noupdate /wb_acq_core_tb/error
add wave -noupdate /wb_acq_core_tb/phy_init_done
add wave -noupdate /wb_acq_core_tb/ddr3_parity
add wave -noupdate /wb_acq_core_tb/ddr3_reset_n
add wave -noupdate /wb_acq_core_tb/ddr3_dq_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_addr_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ba_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ras_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cas_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_we_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cs_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_odt_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_cke_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dm_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_p_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ck_p_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_ck_n_fpga
add wave -noupdate /wb_acq_core_tb/ddr3_dq_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_addr_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ba_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ras_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cas_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_we_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cs_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_odt_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_cke_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dm_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dm_sdram_tmp
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_p_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_dqs_n_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ck_p_sdram
add wave -noupdate /wb_acq_core_tb/ddr3_ck_n_sdram
add wave -noupdate /wb_acq_core_tb/init_calib_complete
add wave -noupdate /wb_acq_core_tb/tg_compare_error
add wave -noupdate /wb_acq_core_tb/ddr_sys_clk_i
add wave -noupdate /wb_acq_core_tb/clk_ref_i
add wave -noupdate /wb_acq_core_tb/ext_dout
add wave -noupdate /wb_acq_core_tb/ext_addr
add wave -noupdate /wb_acq_core_tb/ext_valid
add wave -noupdate /wb_acq_core_tb/ext_sof
add wave -noupdate /wb_acq_core_tb/ext_eof
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_wren
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_data
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_mask
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_end
add wave -noupdate /wb_acq_core_tb/ui_app_addr
add wave -noupdate /wb_acq_core_tb/ui_app_cmd
add wave -noupdate /wb_acq_core_tb/ui_app_en
add wave -noupdate /wb_acq_core_tb/ui_app_rdy
add wave -noupdate /wb_acq_core_tb/ui_app_wdf_rdy
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data_end
add wave -noupdate /wb_acq_core_tb/ui_app_rd_data_valid
add wave -noupdate /wb_acq_core_tb/ui_clk_sync_rst
add wave -noupdate /wb_acq_core_tb/ui_clk_sync_rst_n
add wave -noupdate /wb_acq_core_tb/ui_clk
add wave -noupdate /wb_acq_core_tb/ui_phy_init_done
add wave -noupdate /wb_acq_core_tb/ui_app_req
add wave -noupdate /wb_acq_core_tb/ui_app_gnt
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_data
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_addr
add wave -noupdate /wb_acq_core_tb/dbg_ddr_rb_valid
add wave -noupdate /wb_acq_core_tb/chk_data_err
add wave -noupdate /wb_acq_core_tb/chk_data_err_cnt
add wave -noupdate /wb_acq_core_tb/chk_addr_err
add wave -noupdate /wb_acq_core_tb/chk_addr_err_cnt
add wave -noupdate /wb_acq_core_tb/chk_end
add wave -noupdate /wb_acq_core_tb/chk_pass
add wave -noupdate /wb_acq_core_tb/sys_clk
add wave -noupdate /wb_acq_core_tb/sys_rstn
add wave -noupdate /wb_acq_core_tb/sys_rst
add wave -noupdate /wb_acq_core_tb/adc_clk
add wave -noupdate /wb_acq_core_tb/adc_rstn
add wave -noupdate /wb_acq_core_tb/clk_200mhz
add wave -noupdate /wb_acq_core_tb/clk200mhz_rstn
add wave -noupdate /wb_acq_core_tb/ddr3_sys_clk
add wave -noupdate /wb_acq_core_tb/ddr3_sys_rstn
add wave -noupdate /wb_acq_core_tb/clk_ref
add wave -noupdate /wb_acq_core_tb/sda
add wave -noupdate /wb_acq_core_tb/scl
add wave -noupdate /wb_acq_core_tb/ext_dreq
add wave -noupdate /wb_acq_core_tb/ext_stall
add wave -noupdate /wb_acq_core_tb/sys_rst_n
add wave -noupdate -divider wb_acq_core
add wave -noupdate /wb_acq_core_tb/dut/g_interface_mode
add wave -noupdate /wb_acq_core_tb/dut/g_address_granularity
add wave -noupdate /wb_acq_core_tb/dut/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/g_multishot_ram_size
add wave -noupdate /wb_acq_core_tb/dut/g_fifo_fc_size
add wave -noupdate /wb_acq_core_tb/dut/g_sim_readback
add wave -noupdate /wb_acq_core_tb/dut/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/sys_clk_i
add wave -noupdate /wb_acq_core_tb/dut/sys_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/wb_adr_i
add wave -noupdate /wb_acq_core_tb/dut/wb_dat_i
add wave -noupdate /wb_acq_core_tb/dut/wb_dat_o
add wave -noupdate /wb_acq_core_tb/dut/wb_sel_i
add wave -noupdate /wb_acq_core_tb/dut/wb_we_i
add wave -noupdate /wb_acq_core_tb/dut/wb_cyc_i
add wave -noupdate /wb_acq_core_tb/dut/wb_stb_i
add wave -noupdate /wb_acq_core_tb/dut/wb_ack_o
add wave -noupdate /wb_acq_core_tb/dut/wb_err_o
add wave -noupdate /wb_acq_core_tb/dut/wb_rty_o
add wave -noupdate /wb_acq_core_tb/dut/wb_stall_o
add wave -noupdate /wb_acq_core_tb/dut/data_i
add wave -noupdate /wb_acq_core_tb/dut/dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/ext_trig_i
add wave -noupdate /wb_acq_core_tb/dut/dpram_dout_o
add wave -noupdate /wb_acq_core_tb/dut/dpram_valid_o
add wave -noupdate /wb_acq_core_tb/dut/ext_dout_o
add wave -noupdate /wb_acq_core_tb/dut/ext_valid_o
add wave -noupdate /wb_acq_core_tb/dut/ext_addr_o
add wave -noupdate /wb_acq_core_tb/dut/ext_sof_o
add wave -noupdate /wb_acq_core_tb/dut/ext_eof_o
add wave -noupdate /wb_acq_core_tb/dut/ext_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/ext_stall_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_data_o
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_addr_o
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_valid_o
add wave -noupdate /wb_acq_core_tb/dut/regs_in
add wave -noupdate /wb_acq_core_tb/dut/regs_out
add wave -noupdate /wb_acq_core_tb/dut/wb_slv_adp_out
add wave -noupdate /wb_acq_core_tb/dut/wb_slv_adp_in
add wave -noupdate /wb_acq_core_tb/dut/resized_addr
add wave -noupdate /wb_acq_core_tb/dut/ext_trig_a
add wave -noupdate /wb_acq_core_tb/dut/ext_trig
add wave -noupdate /wb_acq_core_tb/dut/int_trig
add wave -noupdate /wb_acq_core_tb/dut/int_trig_over_thres
add wave -noupdate /wb_acq_core_tb/dut/int_trig_over_thres_d
add wave -noupdate /wb_acq_core_tb/dut/int_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/int_trig_data
add wave -noupdate /wb_acq_core_tb/dut/int_trig_thres
add wave -noupdate /wb_acq_core_tb/dut/hw_trig_pol
add wave -noupdate /wb_acq_core_tb/dut/hw_trig
add wave -noupdate /wb_acq_core_tb/dut/hw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/hw_trig_sel
add wave -noupdate /wb_acq_core_tb/dut/hw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/sw_trig
add wave -noupdate /wb_acq_core_tb/dut/sw_trig_t
add wave -noupdate /wb_acq_core_tb/dut/sw_trig_en
add wave -noupdate /wb_acq_core_tb/dut/trig
add wave -noupdate /wb_acq_core_tb/dut/trig_delay
add wave -noupdate /wb_acq_core_tb/dut/trig_delay_cnt
add wave -noupdate /wb_acq_core_tb/dut/trig_d
add wave -noupdate /wb_acq_core_tb/dut/trig_align
add wave -noupdate /wb_acq_core_tb/dut/acq_fsm_state
add wave -noupdate /wb_acq_core_tb/dut/acq_start
add wave -noupdate /wb_acq_core_tb/dut/acq_start_sync_ext
add wave -noupdate /wb_acq_core_tb/dut/acq_now
add wave -noupdate /wb_acq_core_tb/dut/acq_stop
add wave -noupdate /wb_acq_core_tb/dut/acq_end
add wave -noupdate /wb_acq_core_tb/dut/acq_trig
add wave -noupdate /wb_acq_core_tb/dut/acq_in_pre_trig
add wave -noupdate /wb_acq_core_tb/dut/acq_in_wait_trig
add wave -noupdate /wb_acq_core_tb/dut/acq_in_post_trig
add wave -noupdate /wb_acq_core_tb/dut/samples_wr_en
add wave -noupdate /wb_acq_core_tb/dut/pre_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/post_trig_samples_c
add wave -noupdate /wb_acq_core_tb/dut/shots_nb_c
add wave -noupdate /wb_acq_core_tb/dut/acq_single_shot
add wave -noupdate /wb_acq_core_tb/dut/acq_ddr3_start_addr_full
add wave -noupdate /wb_acq_core_tb/dut/acq_ddr3_start_addr
add wave -noupdate /wb_acq_core_tb/dut/acq_pre_trig_done
add wave -noupdate /wb_acq_core_tb/dut/acq_wait_trig_skip_done
add wave -noupdate /wb_acq_core_tb/dut/acq_post_trig_done
add wave -noupdate /wb_acq_core_tb/dut/samples_cnt
add wave -noupdate /wb_acq_core_tb/dut/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/shots_decr
add wave -noupdate /wb_acq_core_tb/dut/multishot_buffer_sel
add wave -noupdate /wb_acq_core_tb/dut/lmt_acq_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/dpram_addra_cnt
add wave -noupdate /wb_acq_core_tb/dut/dpram_addra_trig
add wave -noupdate /wb_acq_core_tb/dut/dpram_addra_post_done
add wave -noupdate /wb_acq_core_tb/dut/dpram_addrb_cnt
add wave -noupdate /wb_acq_core_tb/dut/dpram_dout
add wave -noupdate /wb_acq_core_tb/dut/dpram_valid
add wave -noupdate /wb_acq_core_tb/dut/fifo_fc_req_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/fifo_fc_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/fifo_fc_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/fifo_fc_full
add wave -noupdate /wb_acq_core_tb/dut/fifo_fc_full_l
add wave -noupdate /wb_acq_core_tb/dut/ext_dout
add wave -noupdate /wb_acq_core_tb/dut/ext_valid
add wave -noupdate /wb_acq_core_tb/dut/ext_sof
add wave -noupdate /wb_acq_core_tb/dut/ext_eof
add wave -noupdate /wb_acq_core_tb/dut/ext_addr
add wave -noupdate /wb_acq_core_tb/dut/ext_dreq
add wave -noupdate /wb_acq_core_tb/dut/ext_stall
add wave -noupdate /wb_acq_core_tb/dut/ddr3_wr_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/ddr3_wr_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/sim_in_rb
add wave -noupdate /wb_acq_core_tb/dut/ddr3_rb_lmt_rb_rst
add wave -noupdate /wb_acq_core_tb/dut/acq_ddr3_rst_n
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_data
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_addr
add wave -noupdate /wb_acq_core_tb/dut/dbg_ddr_rb_valid
add wave -noupdate /wb_acq_core_tb/dut/ddr3_rb_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/ddr3_all_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/ddr3_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/ddr3_all_trans_done_p_fs
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rb_addr_int
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rb_cmd_int
add wave -noupdate /wb_acq_core_tb/dut/ui_app_rb_en_int
add wave -noupdate /wb_acq_core_tb/dut/ui_app_addr_int
add wave -noupdate /wb_acq_core_tb/dut/ui_app_cmd_int
add wave -noupdate /wb_acq_core_tb/dut/ui_app_en_int
add wave -noupdate /wb_acq_core_tb/dut/test_data_en
add wave -noupdate /wb_acq_core_tb/dut/trig_addr
add wave -noupdate /wb_acq_core_tb/dut/c_acq_samples_size
add wave -noupdate /wb_acq_core_tb/dut/c_dpram_depth
add wave -noupdate /wb_acq_core_tb/dut/c_periph_addr_size
add wave -noupdate -divider acq_fsm
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_start_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_now_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_stop_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/pre_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/post_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/samples_cnt_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_single_shot_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_pre_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_wait_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_post_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_pre_trig_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_wait_trig_skip_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_post_trig_done_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_fsm_state_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/shots_decr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_trig_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/multishot_buffer_sel_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/samples_wr_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_fsm_state
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_start
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_stop
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_end
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_end_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_pre_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_wait_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/acq_in_post_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/samples_wr_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/pre_trig_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/pre_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/wait_trig_skip_r
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/wait_trig_skip_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/post_trig_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/post_trig_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/samples_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/shots_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/shots_decr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fsm/single_shot
add wave -noupdate -divider multishot_dpram
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/g_multishot_ram_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/wr_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/addr_rst_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/buffer_sel_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/acq_trig_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/pre_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/post_trig_samples_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/acq_pre_trig_done_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/acq_wait_trig_skip_done_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/acq_post_trig_done_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_addra_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_addra_trig
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_addra_post_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_addrb_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram_valid_t
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram0_dina
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram0_addra
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram0_wea
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram0_addrb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram0_doutb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram1_dina
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram1_addra
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram1_wea
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram1_addrb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/dpram1_doutb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_multishot_dpram/c_dpram_depth
add wave -noupdate -divider fc_fifo
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/g_fifo_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/g_fc_pipe_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fs_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fs_ce_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fs_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/dpram_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/dpram_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/pt_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/pt_dvalid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/pt_wr_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/req_rst_trans_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/passthrough_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/buffer_sel_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_full_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_sof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_eof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_dreq_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_stall_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_din
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_we
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_we_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_we_en_r
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_wr_count
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_data_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_oob_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_valid_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_rd
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_last_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_first_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/ext_stall_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_pkt_sent
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_out_data_pending
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_data_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_data_oob_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_dvalid_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/pre_output_counter_wr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/output_counter_rd
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_rd_empty
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_wr_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_sof
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_eof
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fc_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/req_rst_trans_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/rst_trans_fs_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/rst_trans_ext_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/rst_fc_source_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_in_valid_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_in_valid_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_out_pend_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_pkt_sent_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_pkt_sent_ct_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_pkt_sent_ct_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/shots_sent_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/shots_sent_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_all_trans_done
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/fifo_fc_all_trans_done_sync
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/c_pipe_size
add wave -noupdate -divider fc_source
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/g_pkt_size_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/g_pipe_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_addr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_pkt_sent_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pl_rst_trans_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_dout_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_valid_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_sof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_eof_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_stall_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_dreq_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fifo_fc_first_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fifo_fc_last_data
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_stall_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_valid_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fifo_out_data_pending
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_data_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_addr_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_data_oob_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_dvalid_out
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pre_output_counter_wr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/output_counter_rd
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/pkt_sent
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_data_out_int
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_addr_out_int
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_valid_out_int
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fc_oob_out_int
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fifo_out_pend_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/fifo_diff_pnt_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/output_pipe_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/output_pipe_almost_full
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/output_pipe_empty
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_fc_fifo/cmp_fc_source/c_pipe_almost_full
add wave -noupdate -divider ddr3_iface
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_din_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_addr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_sof_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_eof_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_dreq_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fifo_fc_stall_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/wr_start_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/wr_init_addr_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_rst_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_wdf_data_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_wdf_end_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_wdf_mask_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_wdf_wren_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_wdf_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_req_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ui_app_gnt_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_dout
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_valid_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_valid_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_addr
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_stall_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_dreq_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_stall_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/fc_dreq_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/valid_trans_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/valid_trans_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cnt_all_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_dreq
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_stall
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_dreq_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_stall_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_pkt_sent_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_dreq_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_stall_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_pkt_sent_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/pl_rst_trans
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_data_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_cnt_min
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_cnt_min_ovf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_cnt_min_ovf_s
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_cnt_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_data_valid_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_addr_valid_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_mask_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_data_mask_in
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_rdy_app
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_rdy_app_wdf
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/ddr_req
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/acq_cnt_rst_n
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_fc_payload_ratio
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_mask_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_addr_col_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_addr_bc4_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_addr_bl8_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_addr_ddr_inc
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_pkt_size_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_pipe_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_addr_cnt_width
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_max_addr_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ui_cmd_write
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ui_cmd_read
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_mask_low
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_mask_high
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_data_low
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_data_high
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_addr_ovf_lsb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_addr_ovf_msb
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/c_ddr_addr_ovf_bit
add wave -noupdate -divider ddr3_write_cpm_acq_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/clk_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/cnt_all_pkts_ct_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/cnt_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/cnt_en_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/pkt_ct_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/pkt_cnt_en
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/pkt_ct_cnt_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/shots_cnt_all
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/cmp_acq_ddr3_iface/cmp_acq_cnt/lmt_shots_nb
add wave -noupdate -divider fc_source_ddr3
add wave -noupdate -divider fc_ddr3_readback
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/g_data_width
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/g_addr_width
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/g_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/g_ddr_addr_width
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ext_clk_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_din_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_valid_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_addr_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_sof_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_eof_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_dreq_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/fifo_fc_stall_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/rb_start_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/rb_init_addr_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_rst_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_addr_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_cmd_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_en_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_rdy_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_rd_data_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_rd_data_end_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ui_app_rd_data_valid_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_read_en
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_recv_en
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/valid_trans_in
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/valid_trans_out
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cnt_all_recv_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cnt_all_recv_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cnt_all_req_trans_done_p
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cnt_all_req_trans_done_l
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/issue_rb
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/lmt_valid
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_data_in
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_addr_cnt_out
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_addr_cnt_in
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_addr_cnt_in_d0
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_addr_out
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_valid_out
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/ddr_ui_rdy_t
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_ddr_payload_width
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_ddr_fc_payload_ratio
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_addr_col_inc
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_addr_bc4_inc
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_addr_bl8_inc
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_addr_ddr_inc
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_data_fifo_lsb
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_data_fifo_msb
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_ui_cmd_write
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/c_ui_cmd_read
add wave -noupdate -divider read_ddr3_cnt_recv
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/clk_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/rst_n_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/cnt_all_pkts_ct_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/cnt_all_trans_done_p_o
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/cnt_en_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/pkt_ct_cnt
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/pkt_cnt_en
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/pkt_ct_cnt_all
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/shots_cnt
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/shots_cnt_all
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/dut/gen_ddr3_readback/cmp_acq_ddr3_read/cmp_acq_cnt_recv/lmt_shots_nb
add wave -noupdate -divider data_checker
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_data_width
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_addr_width
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/g_fifo_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/ext_clk_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/ext_rst_n_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_din_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/exp_addr_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_din_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/act_addr_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_pkt_size_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_shots_nb_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_valid_i
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_data_err_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_data_err_cnt_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_end_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/chk_pass_o
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_din
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_we
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_dout
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_rd
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_empty
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_full
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_exp_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_din
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_we
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_dout
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_rd
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_empty
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_full
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/fifo_act_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_in_progress
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_pkt_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_shots_nb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/lmt_valid
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_en
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_done_p
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_chk_done_l
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_match
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err_r
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/data_cmp_err_cnt
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_addr_lsb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_addr_msb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_data_lsb
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/c_data_msb
add wave -noupdate -divider ddr_v3
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/REFCLK_FREQ
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/IODELAY_GRP
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/MMCM_ADV_BANDWIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/CLKFBOUT_MULT_F
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DIVCLK_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/CLKOUT_DIVIDE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nCK_PER_CLK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/tCK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DEBUG_PORT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/SIM_BYPASS_INIT_CAL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nCS_PER_RANK
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/RANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/BANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/CK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/CKE_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/COL_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/CS_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DM_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQ_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ROW_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/BURST_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/BM_CNT_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ADDR_CMD_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ORDERING
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/WRLVL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/PHASE_DETECT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/RTT_NOM
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/RTT_WR
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/OUTPUT_DRV
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/REG_CTRL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nDQS_COL0
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nDQS_COL1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nDQS_COL2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/nDQS_COL3
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_LOC_COL0
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_LOC_COL1
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_LOC_COL2
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DQS_LOC_COL3
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/tPRDI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/tREFI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/tZQI
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ECC
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ECC_TEST
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/TCQ
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/PAYLOAD_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/RST_ACT_LOW
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/INPUT_CLK_TYPE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/STARVE_LIMIT
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sys_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk_ref
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_dq
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_dm
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_ba
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_ras_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cas_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_we_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_reset_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_odt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cke
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_dqs_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_dqs_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_ck_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_ck_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sda
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/scl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_wdf_wren
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_wdf_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_wdf_mask
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_wdf_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_wdf_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_cmd
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_rd_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_rd_data_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_rd_data_valid
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ui_clk_sync_rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ui_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/phy_init_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sys_rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk_ref_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk_ref_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sys_clk_p
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sys_clk_n
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/mmcm_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/iodelay_ctrl_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/sda_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/scl_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk_mem
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/clk_rd_base
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/pd_PSDONE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/pd_PSEN
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/pd_PSINCDEC
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/bank_mach_next
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_parity
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_hi_pri
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/app_ecc_multiple_err_i
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/traffic_wr_data_counts
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/traffic_rd_data_counts
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_cpt_first_edge_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_cpt_second_edge_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_cpt_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_dec_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_dec_rd_dqs
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_dec_rd_fps
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_dq_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_dqs_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_inc_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_inc_dec_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_inc_rd_dqs
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_inc_rd_fps
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_ocb_mon_off
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_off
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_maintain_off
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_maintain_0_only
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rd_active_dly
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rd_bitslip_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rd_clkdly_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rddata
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rdlvl_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rdlvl_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rdlvl_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wl_dqs_inverted
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wl_odelay_dq_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wl_odelay_dqs_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wr_calib_clk_delay
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wr_dq_tap_set
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wr_dqs_tap_set
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wr_tap_set_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_up_all
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_down_all
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_up_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_down_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_up_rsync
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_idel_down_rsync
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_sel_all_idel_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_sel_all_idel_rsync
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_inc_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_dec_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_inc_dqs
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_dec_dqs
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_disab_hyst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_disab_hyst_0
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wrlvl_done
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wrlvl_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_wrlvl_start
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_tap_cnt_during_wrlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rsync_tap_cnt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_phy_pd
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_phy_read
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_phy_rdlvl
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_phy_top
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_msb_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_rd_data_edge_detect
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_sel_idel_cpt
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_sel_idel_rsync
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/dbg_pd_byte_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/modify_enable_sel
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/vio_data_mode
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/vio_addr_mode
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs0_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs0_control
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs0_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs0_trig
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs1_async_in
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs1_control
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs2_async_in
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs2_control
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs3_async_in
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs3_control
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs4_clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs4_control
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ddr3_cs4_sync_out
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/SYSCLK_PERIOD
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/SIMULATION
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/DATA_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/ADDR_MODE
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/APP_DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/APP_MASK_WIDTH
add wave -noupdate -divider ddr_v6_ui_top
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/TCQ
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/APP_DATA_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/APP_MASK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/BANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/COL_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/CWL
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ECC
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ECC_TEST
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ORDERING
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/RANKS
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/RANK_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ROW_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/MEM_ADDR_ORDER
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ADDR_WIDTH
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/accept
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_correct_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/correct_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/accept_ns
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_cmd
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_hi_pri
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_raw_not_ecc
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_sz
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_wdf_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_wdf_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_wdf_mask
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_wdf_wren
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/clk
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ecc_multiple
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data_offset
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rst
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data_en
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data_offset
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_ecc_multiple_err
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_rd_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_rd_data_end
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_rd_data_valid
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_wdf_rdy
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/bank
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/cmd
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/col
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/data_buf_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/hi_priority
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rank
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/raw_not_ecc
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/row
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/size
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/use_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data_mask
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ram_init_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/ram_init_done_r
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_accepted
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_buf_full
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rd_data_buf_addr_r
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_accepted
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_data_buf_addr
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/wr_req_16
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/app_addr_temp
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rst_reg
add wave -noupdate /wb_acq_core_tb/cmp_ddr_v6/u_memc_ui_top/u_ui_top/rst_final
add wave -noupdate -divider ddr3_model_3
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[3]/u_comp_ddr3/odt}
add wave -noupdate -divider ddr3_model_2
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[2]/u_comp_ddr3/odt}
add wave -noupdate -divider ddr3_model_1
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[1]/u_comp_ddr3/odt}
add wave -noupdate -divider ddr3_model_0
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/rst_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ck}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ck_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cke}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ras_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/cas_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/we_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dm_tdqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/ba}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/addr}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dq}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dqs}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/dqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/tdqs_n}
add wave -noupdate {/wb_acq_core_tb/mem_rnk[0]/mem_16/gen_mem/gen_mem[0]/u_comp_ddr3/odt}
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/cmp_exp_data_fifo/g_size
add wave -noupdate /wb_acq_core_tb/cmp_data_checker/cmp_act_data_fifo/g_size
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {104092500000 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 204
configure wave -valuecolwidth 190
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {101348254889 fs} {110764662691 fs}
